### ISSUE TITLE
Capybara stuck when is chromedriver

### ISSUE THREAD

**Issue by roroco** [teamcapybara/capybara#1819]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:

2.11.0
Driver Information (and browser if relevant):

```
roroco@roroco ~/Dropbox/rbs/ro_wemedia $ chromedriver -v
ChromeDriver 2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320)
```

## Expected Behavior
show chrome window
## Actual Behavior
raise error:(it stuck for long time and raise this error)

```
Uncaught exception: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.4.0-21-generic x86_64)
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/http/default.rb:86:in `request'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/bridge.rb:647:in `raw_execute'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/bridge.rb:109:in `create_session'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/remote/bridge.rb:69:in `initialize'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/chrome/bridge.rb:42:in `initialize'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/common/driver.rb:61:in `new'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver/common/driver.rb:61:in `for'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2/lib/selenium/webdriver.rb:82:in `for'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.11.0/lib/capybara/selenium/driver.rb:22:in `browser'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.11.0/lib/capybara/selenium/driver.rb:55:in `visit'
	/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.11.0/lib/capybara/session.rb:246:in `visit'
	/home/roroco/Dropbox/rbs/ro_wemedia/exe.rb:9:in `<top (required)>'
```
## Steps to reproduce

```
require 'capybara'

Capybara.register_driver :crm do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome)
end

se = Capybara::Session.new(:crm)
se.visit("google.com")

```

here is my full env:

```
roroco@roroco ~/Dropbox/rbs/ro_wemedia $ bundle show selenium
/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.0.2
roroco@roroco ~/Dropbox/rbs/ro_wemedia $ bundle show capybara
/home/roroco/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.11.0
roroco@roroco ~/Dropbox/rbs/ro_wemedia $ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
roroco@roroco ~/Dropbox/rbs/ro_wemedia $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
roroco@roroco ~/Dropbox/rbs/ro_wemedia $ chromedriver -v
ChromeDriver 2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320)
roroco@roroco ~/Dropbox/rbs/ro_wemedia $ google-chrome -version
Google Chrome 55.0.2883.87 

```

**Comment by roroco** [comment]
I fix it, see [my stackoverflow question](http://stackoverflow.com/questions/41416278/capybara-stuck-when-use-chromedriver/41421522#41421522)
