### ISSUE TITLE
Using capybara with `debuggerAddress` cause infinite loading

### ISSUE THREAD

**Issue by BjornMelgaard** [teamcapybara/capybara#1895]
## Meta
Capybara Version: capybara (2.14.4)
Driver Information (and browser if relevant): archlinux, [chromedriver](https://aur.archlinux.org/packages/chromedriver/) 2.30-1, google-chrome-stable 60.0.3112.78

[repo](https://github.com/BjornMelgaard/vue-todolist)

I want to use capybara-rspec tests in existing session of chrome (no external chrome, use my chrome, just open new tab and run tests, then close tab)
I have found that this is [feasible using debuggerAddress](https://bugs.chromium.org/p/chromedriver/issues/detail?id=710#c3)

## How to do it without capy
```
// close all chrome windows
$ google-chrome-stable --remote-debugging-port=4444
// chrome opened with my profile
$ pry
>  require 'selenium-webdriver'
>  options = Selenium::WebDriver::Chrome::Options.new
>  options.add_option('debuggerAddress', '127.0.0.1:4444')
>  driver = Selenium::WebDriver.for :chrome, options: options
.... currently opened page is driver.current_url
```

## Steps to reproduce
// spec/config

```
# usage - close chrome and 'google-chrome-stable --remote-debugging-port=4444'
require 'selenium-webdriver'

Capybara.register_driver :local_chrome do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_option('debuggerAddress', '127.0.0.1:4444')

  Capybara::Selenium::Driver.new(app,
                                  browser: :chrome,
                                  options: options)
end

Capybara.javascript_driver = :local_chrome
Capybara.default_driver    = :local_chrome

server_port = ENV['PORT']              # port of rails api 
client_port = ENV['CLIENT_PORT'] # port of my spa, I want test to 

if !server_port || !client_port
  puts 'Warning: No PORT' unless server_port
  puts 'Warning: No CLIENT_PORT' unless client_port
  puts 'Feature tests will probably fail'
else
  Capybara.server_port = server_port
  Capybara.app_host = "http://localhost:#{client_port}"
end
```

then in some feature test `visit('/')` or `current_url` is causing infinite loading

**Comment by BjornMelgaard** [comment]
any help?

**Comment by BjornMelgaard** [comment]
If wait long enough 

```
          RuntimeError:
            Rack application timed out during boot
          # /home/bjorn/.rvm/gems/ruby-2.4.1@vue-todolist/gems/capybara-2.14.4/lib/capybara/server.rb:108:in `rescue in boot'
          # /home/bjorn/.rvm/gems/ruby-2.4.1@vue-todolist/gems/capybara-2.14.4/lib/capybara/server.rb:98:in `boot'
          # /home/bjorn/.rvm/gems/ruby-2.4.1@vue-todolist/gems/capybara-2.14.4/lib/capybara/session.rb:88:in `initialize'
          # /home/bjorn/.rvm/gems/ruby-2.4.1@vue-todolist/gems/capybara-2.14.4/lib/capybara.rb:304:in `new'
          # /home/bjorn/.rvm/gems/ruby-2.4.1@vue-todolist/gems/capybara-2.14.4/lib/capybara.rb:304:in `current_session'
          # /home/bjorn/.rvm/gems/ruby-2.4.1@vue-todolist/gems/site_prism-2.9/lib/site_prism/page.rb:15:in `page'
          # /home/bjorn/.rvm/gems/ruby-2.4.1@vue-todolist/gems/capybara-2.14.4/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
          # /home/bjorn/.rvm/gems/ruby-2.4.1@vue-todolist/gems/site_prism-2.9/lib/site_prism/page.rb:31:in `load'
          # ./spec/features/authentication_spec.rb:8:in `block (3 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # Timeout::Error:
          #   execution expired
          #   /home/bjorn/.rvm/gems/ruby-2.4.1@vue-todolist/gems/capybara-2.14.4/lib/capybara/server.rb:105:in `join'

```

**Comment by BjornMelgaard** [comment]
it was empty port string
