### ISSUE TITLE
Source maps are not being applied to error stack when using chrome selenium driver

### ISSUE THREAD

**Issue by faucct** [teamcapybara/capybara#1941]
## Meta
Capybara Version:
2.15.4
Driver Information (and browser if relevant):
selenium-webdriver 3.5.1 with Chrome 62.0.3202.94

## Expected Behavior

When throwing an error in the webpack compiled code and reading the logs like this - `page.driver.browser.manage.logs.get(:browser)` or `page.driver.browser.manage.logs.get(:driver)` I should see the stack traces with applied source maps, like the chrome browser does when I pause the specs and connect to the test server myself.

## Actual Behavior

Browser logs give me a short version of what I see in a console, I guess a first line:

```
#<Selenium::WebDriver::LogEntry:0x007f8cc69d1340 @level="SEVERE", @timestamp=1511336744134, @message="http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js 10564:27 Uncaught Error: wtf">
#<Selenium::WebDriver::LogEntry:0x007f8cc69d1278 @level="SEVERE", @timestamp=1511336744135, @message="http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js 41599:12 \"The above error occurred in one of your React components:\\n    in Unknown (created by Connect(Component))\\n    in Connect(Component) (created by Route)\\n    in Route (created by _class)\\n    in Switch (created by _class)\\n    in div (created by _class)\\n    in Router (created by ConnectedRouter)\\n    in ConnectedRouter (created by _class)\\n    in Provider (created by _class)\\n    in _class\\n\\nConsider adding an error boundary to your tree to customize error handling behavior.\\nVisit https://fb.me/react-error-boundaries to learn more about error boundaries.\"">
#<Selenium::WebDriver::LogEntry:0x007f8cc69d11b0 @level="SEVERE", @timestamp=1511336744135, @message="http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js 1487:18 \"uncaught at authenticate\"">
```

Driver logs have a whole stack trace, but still no source maps applied:

```
#<Selenium::WebDriver::LogEntry:0x007f8cc4f7ac80 @level="DEBUG", @timestamp=1511336744134, @message="DEVTOOLS EVENT Runtime.exceptionThrown {\n   \"exceptionDetails\": {\n      \"columnNumber\": 27,\n      \"exception\": {\n         \"className\": \"Error\",\n         \"description\": \"Error: wtf\\n    at http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js:10565:28\\n    at mountIndeterminateComponent (http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182...\",\n         \"objectId\": \"{\\\"injectedScriptId\\\":1,\\\"id\\\":1}\",\n         \"preview\": {\n            \"description\": \"Error: wtf\\n    at http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js:10565:28\\n    at mountIndeterminateComponent (http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182...\",\n            \"overflow\": false,\n            \"properties\": [ {\n               \"name\": \"stack\",\n               \"type\": \"string\",\n               \"value\": \"Error: wtf\\n    at http://127.0.0.1:64157/packs-tes…est/application-b949d8eaf74d406182d1.js:42831:24)\"\n            }, {\n               \"name\": \"message\",\n               \"type\": \"string\",\n               \"value\": \"wtf\"\n            } ],\n            \"subtype\": \"error\",\n            \"type\": \"object\"\n         },\n         \"subtype\": \"error\",\n         \"type\": \"object\"\n      },\n      \"exceptionId\": 1,\n      \"executionContextId\": 1,\n      \"lineNumber\": 10564,\n      \"stackTrace\": {\n         \"callFrames\": [ {\n            \"columnNumber\": 27,\n            \"functionName\": \"\",\n            \"lineNumber\": 10564,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 14,\n            \"functionName\": \"mountIndeterminateComponent\",\n            \"lineNumber\": 39888,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 15,\n            \"functionName\": \"beginWork\",\n            \"lineNumber\": 40079,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 15,\n            \"functionName\": \"performUnitOfWork\",\n            \"lineNumber\": 42074,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 25,\n            \"functionName\": \"workLoop\",\n            \"lineNumber\": 42138,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 13,\n            \"functionName\": \"callCallback\",\n            \"lineNumber\": 32370,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 15,\n            \"functionName\": \"invokeGuardedCallbackDev\",\n            \"lineNumber\": 32409,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 26,\n            \"functionName\": \"invokeGuardedCallback\",\n            \"lineNumber\": 32266,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 6,\n            \"functionName\": \"renderRoot\",\n            \"lineNumber\": 42216,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 23,\n            \"functionName\": \"performWorkOnRoot\",\n            \"lineNumber\": 42830,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 6,\n            \"functionName\": \"performWork\",\n            \"lineNumber\": 42782,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 6,\n            \"functionName\": \"requestWork\",\n            \"lineNumber\": 42691,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 10,\n            \"functionName\": \"scheduleWorkImpl\",\n            \"lineNumber\": 42574,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 11,\n            \"functionName\": \"scheduleWork\",\n            \"lineNumber\": 42536,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 6,\n            \"functionName\": \"enqueueSetState\",\n            \"lineNumber\": 38034,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 15,\n            \"functionName\": \"Component.setState\",\n            \"lineNumber\": 23206,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 15,\n            \"functionName\": \"onStateChange\",\n            \"lineNumber\": 12190,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 6,\n            \"functionName\": \"dispatch\",\n            \"lineNumber\": 12458,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, {\n            \"columnNumber\": 21,\n            \"functionName\": \"\",\n            \"lineNumber\": 79206,\n            \"scriptId\": \"26\",\n            \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n         }, \"...\" ]\n      },\n      \"text\": \"Uncaught\",\n      \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n   },\n   \"timestamp\": 1511336743217.27\n}\n">
#<Selenium::WebDriver::LogEntry:0x007f8cc4f7abb8 @level="DEBUG", @timestamp=1511336744135, @message="DEVTOOLS EVENT Runtime.consoleAPICalled {\n   \"args\": [ {\n      \"type\": \"string\",\n      \"value\": \"The above error occurred in one of your React components:\\n    in Unknown (created by Connect(Component))\\n    in Connect(Component) (created by Route)\\n    in Route (created by _class)\\n    in Switch ...\"\n   } ],\n   \"executionContextId\": 1,\n   \"stackTrace\": {\n      \"callFrames\": [ {\n         \"columnNumber\": 12,\n         \"functionName\": \"logCapturedError\",\n         \"lineNumber\": 41599,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 8,\n         \"functionName\": \"captureError\",\n         \"lineNumber\": 42390,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 21,\n         \"functionName\": \"renderRoot\",\n         \"lineNumber\": 42241,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 23,\n         \"functionName\": \"performWorkOnRoot\",\n         \"lineNumber\": 42830,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 6,\n         \"functionName\": \"performWork\",\n         \"lineNumber\": 42782,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 6,\n         \"functionName\": \"requestWork\",\n         \"lineNumber\": 42691,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 10,\n         \"functionName\": \"scheduleWorkImpl\",\n         \"lineNumber\": 42574,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 11,\n         \"functionName\": \"scheduleWork\",\n         \"lineNumber\": 42536,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 6,\n         \"functionName\": \"enqueueSetState\",\n         \"lineNumber\": 38034,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 15,\n         \"functionName\": \"Component.setState\",\n         \"lineNumber\": 23206,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 15,\n         \"functionName\": \"onStateChange\",\n         \"lineNumber\": 12190,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 6,\n         \"functionName\": \"dispatch\",\n         \"lineNumber\": 12458,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 21,\n         \"functionName\": \"\",\n         \"lineNumber\": 79206,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 17,\n         \"functionName\": \"dispatch\",\n         \"lineNumber\": 25586,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 11,\n         \"functionName\": \"\",\n         \"lineNumber\": 1512,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 51,\n         \"functionName\": \"\",\n         \"lineNumber\": 22377,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 4,\n         \"functionName\": \"exec\",\n         \"lineNumber\": 21036,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 4,\n         \"functionName\": \"flush\",\n         \"lineNumber\": 21077,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 4,\n         \"functionName\": \"asap\",\n         \"lineNumber\": 21050,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, \"...\" ]\n   },\n   \"timestamp\": 1511336743221.993,\n   \"type\": \"error\"\n}\n">
#<Selenium::WebDriver::LogEntry:0x007f8cc4f79fb0 @level="DEBUG", @timestamp=1511336744135, @message="DEVTOOLS EVENT Runtime.consoleAPICalled {\n   \"args\": [ {\n      \"type\": \"string\",\n      \"value\": \"uncaught at authenticate\"\n   }, {\n      \"type\": \"string\",\n      \"value\": \"Error: wtf\\n    at http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js:10565:28\\n    at mountIndeterminateComponent (http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182...\"\n   } ],\n   \"executionContextId\": 1,\n   \"stackTrace\": {\n      \"callFrames\": [ {\n         \"columnNumber\": 18,\n         \"functionName\": \"log\",\n         \"lineNumber\": 1487,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 4,\n         \"functionName\": \"logError\",\n         \"lineNumber\": 22098,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 8,\n         \"functionName\": \"\",\n         \"lineNumber\": 22381,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 4,\n         \"functionName\": \"exec\",\n         \"lineNumber\": 21036,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 4,\n         \"functionName\": \"flush\",\n         \"lineNumber\": 21077,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 4,\n         \"functionName\": \"asap\",\n         \"lineNumber\": 21050,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 68,\n         \"functionName\": \"runPutEffect\",\n         \"lineNumber\": 22374,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 306,\n         \"functionName\": \"runEffect\",\n         \"lineNumber\": 22323,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 8,\n         \"functionName\": \"next\",\n         \"lineNumber\": 22203,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      }, {\n         \"columnNumber\": 6,\n         \"functionName\": \"currCb\",\n         \"lineNumber\": 22276,\n         \"scriptId\": \"26\",\n         \"url\": \"http://127.0.0.1:64157/packs-test/application-b949d8eaf74d406182d1.js\"\n      } ]\n   },\n   \"timestamp\": 1511336743225.446,\n   \"type\": \"error\"\n}\n">

```

## Steps to reproduce
I will have that if needed. I think that you can just throw a javascript error in your source code and get the logs with the commands mentioned before.

**Comment by twalpole** [comment]
This info is returned from chromedriver via selenium.  If you want more info you'll need to file an issue with one of those projects.  I would guess chromedriver.  This has nothing to do with Capybara.

**Comment by faucct** [comment]
OK. I have just wanted to make sure that nobody is familiar with the issue here. Thanks.
