### ISSUE TITLE
Multidimensional array throwing NoMethodError error, breaking spec

### ISSUE THREAD

**Issue by speasley** [teamcapybara/capybara#2030]
## Meta
Capybara Version:
2.18.0
Driver Information (and browser if relevant):
selenium-webdriver (3.11.0), headless

## Expected Behavior
A passing spec when accessing a value inside a multidimensional array.

## Actual Behavior
```
Failure/Error: h3 = @choices.select{ |x| x[1] == @job.job_type }.first.first
     
     ActionView::Template::Error:
       undefined method `take' for nil:NilClass
     # ./app/views/jobs/show.html.slim:6:in `_app_views_jobs_show_html_slim___1109481342974638443_70145170011240'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/audited-4.7.1/lib/audited/sweeper.rb:14:in `around'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/audited-4.7.1/lib/audited/sweeper.rb:14:in `around'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/etag.rb:25:in `call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/conditional_get.rb:25:in `call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/head.rb:12:in `call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:232:in `context'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:226:in `call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/rack/logger.rb:36:in `call_app'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/rack/logger.rb:24:in `block in call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/rack/logger.rb:24:in `call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/runtime.rb:22:in `call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/sendfile.rb:111:in `call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/engine.rb:522:in `call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/urlmap.rb:68:in `block in call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/urlmap.rb:53:in `each'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/urlmap.rb:53:in `call'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-test-0.8.3/lib/rack/mock_session.rb:29:in `request'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-test-0.8.3/lib/rack/test.rb:251:in `process_request'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-test-0.8.3/lib/rack/test.rb:129:in `custom_request'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/rack-test-0.8.3/lib/rack/test.rb:58:in `get'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/capybara-2.18.0/lib/capybara/rack_test/browser.rb:69:in `process'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/capybara-2.18.0/lib/capybara/rack_test/browser.rb:41:in `process_and_follow_redirects'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/capybara-2.18.0/lib/capybara/rack_test/browser.rb:22:in `visit'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/capybara-2.18.0/lib/capybara/rack_test/driver.rb:44:in `visit'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/capybara-2.18.0/lib/capybara/session.rb:274:in `visit'
     # /Users/speasley/.rvm/gems/ruby-2.4.1/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/features/jobs_spec.rb:30:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `first' for nil:NilClass
     #   ./app/views/jobs/show.html.slim:6:in `_app_views_jobs_show_html_slim___1109481342974638443_70145170011240'
```

## Steps to reproduce
Any of these methods will throw essentially the same error:
`h3 = @choices.select{ |x| x[1] == @job.job_type }.first[0] #undefined method `[]' for nil:NilClass`
`h3 = @choices.select{ |x| x[1] == @job.job_type }[0].first #undefined method `first' for nil:NilClass`
`h3 = @choices.select{ |x| x[1] == @job.job_type }.first.shift #undefined method `shift' for nil:NilClass`
`h3 = @choices.select{ |x| x[1] == @job.job_type }.shift.first #undefined method `first' for nil:NilClass`
`h3 = @choices.select{ |x| x[1] == @job.job_type }.first.first #undefined method `first' for nil:NilClass`
`h3 = @choices.select{ |x| x[1] == @job.job_type }.first.at(0) #undefined method `at' for nil:NilClass`
`h3 = @choices.select{ |x| x[1] == @job.job_type }.at(0).first #undefined method `first' for nil:NilClass`

However, the array is not nil. The test passes fine one level shallower, regardless of method:
`h3 = @choices.select{ |x| x[1] == @job.job_type }[0]`
`h3 = @choices.select{ |x| x[1] == @job.job_type }.shift`
`h3 = @choices.select{ |x| x[1] == @job.job_type }.first`
`h3 = @choices.select{ |x| x[1] == @job.job_type }.at(0)`

**Comment by speasley** [comment]
I thought it was a Capybara error because it doesn't throw an error anywhere else, only in the spec. It renders properly. The spec is the only place where an error is thrown. I meant to include the spec that throws the error: 

```
it "should show a job's page" do
   visit job_path(job)
   expect(page).to have_content(job.title)
end
```

**Comment by twalpole** [comment]
But the error is thrown in your view template -- The only thing Capybara is doing in that backtrace is making a request.  Your data for the view is not loaded correctly - that means either you're not putting the correct info into the DB for @chocies (I'm assuming it's loaded from the DB because there is nothing that describes what it is) the test or the job_type isn't matching any of the data that is loaded.  Look at what '@choices` and `@job.job_type` are in whichever controller is handling this request.  Either `@choices` will be an empty array - or none of its entries will have the correct `job_type` - Capybara wouldn't affect any of that.

**Comment by speasley** [comment]
Thanks for the guidance. I'll keep digging around.
