### ISSUE TITLE
"stale element reference" with Chrome and verifying an element is not on the page that has been navigated away from

### ISSUE THREAD

**Issue by shepmaster** [teamcapybara/capybara#2109]
## Meta

- Capybara 3.9.0
- Selenium Webdriver 3.14.1
- Webdrivers 3.3.2
- Ruby 2.5.1p57
- ChromeDriver 70.0.3538.16
- Chrome 69.0.3497.100
- macOS 10.14 (18A391)

## Expected Behavior

I should be able to navigate away from a page and check to see that the browser no longer contains content from the previous page.

## Actual Behavior

```
Exception: Selenium::WebDriver::Error::StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=70.0.3538.16 (16ed95b41bb05e565b11fb66ac33c660b721f778),platform=Mac OS X 10.14.0 x86_64)
--
 0: gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
 1: gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
 2: gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
 3: gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
 4: gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
 5: gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
 6: gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
 7: gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/oss/bridge.rb:584:in `execute'
 8: gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/remote/oss/bridge.rb:494:in `element_text'
 9: gems/selenium-webdriver-3.14.1/lib/selenium/webdriver/common/element.rb:136:in `text'
10: gems/capybara-3.9.0/lib/capybara/selenium/node.rb:6:in `visible_text'
11: gems/capybara-3.9.0/lib/capybara/node/element.rb:58:in `block in text'
12: gems/capybara-3.9.0/lib/capybara/node/base.rb:77:in `synchronize'
13: gems/capybara-3.9.0/lib/capybara/node/element.rb:58:in `text'
14: gems/capybara-3.9.0/lib/capybara/queries/text_query.rb:96:in `text'
15: gems/capybara-3.9.0/lib/capybara/queries/text_query.rb:21:in `resolve_for'
16: gems/capybara-3.9.0/lib/capybara/node/matchers.rb:725:in `block in _verify_text'
17: gems/capybara-3.9.0/lib/capybara/node/base.rb:82:in `synchronize'
18: gems/capybara-3.9.0/lib/capybara/node/matchers.rb:724:in `_verify_text'
19: gems/capybara-3.9.0/lib/capybara/node/matchers.rb:655:in `assert_no_text'
20: gems/capybara-3.9.0/lib/capybara/node/matchers.rb:689:in `block in has_no_text?'
21: gems/capybara-3.9.0/lib/capybara/node/matchers.rb:737:in `make_predicate'
22: gems/capybara-3.9.0/lib/capybara/node/matchers.rb:689:in `has_no_text?'
23: gems/capybara-3.9.0/lib/capybara/session.rb:732:in `block (2 levels) in <class:Session>'
24: repro.rb:13:in `block in <top (required)>'
25: gems/capybara-3.9.0/lib/capybara/session.rb:332:in `within'
26: gems/capybara-3.9.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
27: repro.rb:11:in `<top (required)>'
28: gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
29: gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `block in load'
30: gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
31: gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
32: (pry):19:in `<main>'
33: gems/pry-0.11.3/lib/pry/pry_instance.rb:355:in `eval'
34: gems/pry-0.11.3/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
35: gems/pry-0.11.3/lib/pry/pry_instance.rb:323:in `handle_line'
36: gems/pry-0.11.3/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
37: gems/pry-0.11.3/lib/pry/pry_instance.rb:242:in `catch'
38: gems/pry-0.11.3/lib/pry/pry_instance.rb:242:in `block in eval'
39: gems/pry-0.11.3/lib/pry/pry_instance.rb:241:in `catch'
40: gems/pry-0.11.3/lib/pry/pry_instance.rb:241:in `eval'
41: gems/pry-0.11.3/lib/pry/repl.rb:77:in `block in repl'
42: gems/pry-0.11.3/lib/pry/repl.rb:67:in `loop'
43: gems/pry-0.11.3/lib/pry/repl.rb:67:in `repl'
44: gems/pry-0.11.3/lib/pry/repl.rb:38:in `block in start'
45: gems/pry-0.11.3/lib/pry/input_lock.rb:61:in `__with_ownership'
46: gems/pry-0.11.3/lib/pry/input_lock.rb:79:in `with_ownership'
47: gems/pry-0.11.3/lib/pry/repl.rb:38:in `start'
48: gems/pry-0.11.3/lib/pry/repl.rb:13:in `start'
49: gems/pry-0.11.3/lib/pry/pry_class.rb:192:in `start'
50: gems/pry-byebug-3.6.0/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
51: gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:62:in `start'
52: gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:17:in `start'
53: gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:97:in `perform'
54: gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
55: gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
56: gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
57: gems/railties-5.1.6/lib/rails/command/base.rb:63:in `perform'
58: gems/railties-5.1.6/lib/rails/command.rb:44:in `invoke'
59: gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
```

This does work in PhantomJS, but I'm attempting to move to something more supported.

## Steps to reproduce

```ruby
require 'capybara'
require 'capybara/dsl'
require 'webdrivers'

include Capybara::DSL

Capybara.current_driver = :selenium_chrome
Capybara.app_host = 'http://www.google.com'

visit('/')
within('#viewport') do
  page.click_on("About") # Navigate to another page
  page.has_no_content? "Lucky" # Assert that the page has changed
end
```

**Comment by shepmaster** [comment]
> doesn't assert anything, it's a boolean so it should return true/false

Yep, our original test does use `expect(page).to have_no_text('Lucky')`, I simply removed it to provide a minimal reproduction, as requested by the issue template.

> you're `within` an element that's going away

I figured as much, but the title was already getting long. 

I always had the impression that `within` simply added context to each selector queried within it, making it equivalent to `page.has_no_selector('#viewport', text: 'Lucky')`.

Splitting it into multiple blocks 

```ruby
within('#viewport') { page.click_on("About") }
within('#viewport') { page.has_no_content? "Lucky" }
```

yields

```
Capybara::ElementNotFound: Unable to find css "#viewport"
```

From this, it sounds like `within` eagerly retrieves a node from the driver and hangs on to it; is that more accurate? 

Any idea why the different behavior with PhantomJS? Most likely to be a timing issue, where Chrome navigates the page more quickly?

**Comment by twalpole** [comment]
`within` basically changes what `page` is.  Inside the `within` block `page` refers to the element that matches whatever was passed to `within`.   If the new page also had a `#viewport` element then (iirc) the within block should reload that element and refer to the new element, but since there isn't one `page` is now stale.  I'm not really sure why PhantomJS didn't fail with that, but If I had to guess I think PhantomJS holds on to a cache of elements longer than modern Chrome does, so PhantomJS still had a copy of the `#viewport` element even though it was no longer on the active page.

**Comment by shepmaster** [comment]
Thank you for your help, as always!
