### ISSUE TITLE
webdriver/atoms/isDisplayed.js is missing

### ISSUE THREAD

**Issue by ahorek** [teamcapybara/capybara#2151]
## Meta
Capybara Version:
3.13.0
Driver Information (and browser if relevant):
selenium-webdriver 3.11.0 with Headless Chrome 71.0.3578.80ChromeDriver 2.43.600233 

## Expected Behavior
it works fine on capybara 3.12.0 and older versions

## Actual Behavior
capybara 3.13.0 fails
```
Failure/Error: expect(page).to have_css(".form-actions input[type='submit']")

     Errno::ENOENT:
        No such file or directory @ rb_sysopen - /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/atoms/isDisplayed.js
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/atoms.rb:8:in `read'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/atoms.rb:8:in `read_atom'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/selenium/extensions/find.rb:77:in `is_displayed_atom'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/selenium/extensions/find.rb:26:in `find_by'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/selenium/extensions/find.rb:11:in `find_css'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/node/base.rb:100:in `find_css'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/queries/selector_query.rb:190:in `find_nodes_by_selector_format'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/queries/selector_query.rb:125:in `block in resolve_for'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/node/base.rb:77:in `synchronize'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/queries/selector_query.rb:124:in `resolve_for'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/node/matchers.rb:735:in `block in _verify_selector_result'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/node/base.rb:83:in `synchronize'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/node/matchers.rb:734:in `_verify_selector_result'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/node/matchers.rb:110:in `assert_selector'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/session.rb:744:in `block (2 levels) in <class:Session>'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/rspec/matchers/have_selector.rb:10:in `element_matches?'
      # /usr/local/rvm/gems/ruby-2.5.1-railsexpress/gems/capybara-3.13.0/lib/capybara/rspec/matchers/base.rb:43:in `matches?'
```
is looks like webdriver/atoms/isDisplayed.js was added just recently in selenium-webdriver-3.14.1

are older webdrivers unsupported or is there a way to add a fallback for older versions?

**Comment by twalpole** [comment]
Sorry, this was unintended, I will get a 3.13.1 fix out later today. In the meantime please rollback to 3.12.x or set a DISABLE_CAPYBARA_SELENIUM_OPTIMIZATIONS environment variable

**Comment by ahorek** [comment]
Ok, thanks

**Comment by twalpole** [comment]
Fix for this is in the `issue_2151` branch -- Will release 3.13.1 once the tests all pass on Travis

**Comment by twalpole** [comment]
Closing via 3.13.1 release - although I would recommend updating your selenium-webdriver at some point.  3.11 is nearly a year old which is a long time in testing tools.

**Comment by ahorek** [comment]
thanks for the patch @twalpole . My tests are green again.

I froze the version because selenium-webdriver many times introduced a breaking change in a minor version, but I'll see what I can do.
