### ISSUE TITLE
Capybara executes assertions before page is loaded (Rack driver)

### ISSUE THREAD

**Issue by marko-avlijas** [teamcapybara/capybara#2154]
## Meta

I guess I should get the versions from Gemfile.lock?

Capybara Version: 2.15
Driver Information (and browser if relevant):
      rack (~> 2.0)
      rack-test (>= 0.6.3)

## Expected Behavior
I have this code:
```
      visit path
      assert_css "a.nav-item.active", text: "#{page_title} (current)"

```
Capybara should wait for page to render before it starts assert_css. 

## Actual Behavior

When I put debugger in code, I see that test fails before code that renders nav links is executed.

 FAIL["test_current_page_is_displayed_as_active_in_navbar", #<Minitest::Reporters::Suite:0x000055a5680a71a8 @name="LayoutLinksCapybaraTest">, 2.811533664993476]
 test_current_page_is_displayed_as_active_in_navbar#LayoutLinksCapybaraTest (2.81s)
        expected to find css ".nav-item.dropdown.active" but there were no matches
        test/capybara/layout_links_test.rb:64:in `assert_dropdown_account_is_active'
        test/capybara/layout_links_test.rb:44:in `block in <class:LayoutLinksCapybaraTest>'

  86/86: [=====================================] 100% Time: 00:00:05, Time: 00:00:05

Finished in 5.44153s
86 tests, 537 assertions, 1 failures, 0 errors, 0 skips

## Steps to reproduce

```
git clone git@github.com:marko-avlijas/members_only.git
cd members_only
git checkout 9e74c6f    # HEAD is now at 9e74c6f... Capybara bug?
bundle
bundle exec guard

```
It's the only failing test.

I am sorry but `rails test` won't work. This is my first rails app from scratch so my setup is unconventional and for some reason rails is refusing to load faker, but guard isn't.

**Comment by twalpole** [comment]
I’m about to get on a plane so won’t be able to check this until later today, but if you are actually using the rack-test driver there is no rendering to take place because it doesn’t support JS or most CSS - if your test is dependent on JS/CSS you need to be using one of the other drivers (Selenium, Apparition, etc)

**Comment by marko-avlijas** [comment]
There is no js in this app. :) By rendering I meant like rails `render html: 'something'`

**Comment by twalpole** [comment]
Then it’s impossible for the rack-test driver not to render - its single threaded so it calls the rails app, gets the response and then runs the assert.  Check `page.html` after the visit . Either your app has a bug or what you’re testing for isn’t correct
