### ISSUE TITLE
Finding an available port fails randomly

### ISSUE THREAD

**Issue by lukaso** [teamcapybara/capybara#2245]
## Meta
Capybara Version:
All versions, but specifically seen on both 2.18 and 3.28

## Expected Behavior
Capybara should reliably start servers (such as Puma) every time.

## Actual Behavior
Booting a server fails randomly (and rarely) with `Errno::EADDRINUSE`

```
Capybara starting Puma...
* Version 3.12.0 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:42080
#<Thread:0x000055db476dab00@/home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/capybara-3.28.0/lib/capybara/server.rb:74 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	11: from /home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/capybara-3.28.0/lib/capybara/server.rb:75:in `block in boot'
	10: from /home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/capybara-3.28.0/lib/capybara/registrations/servers.rb:4:in `block in <top (required)>'
	 9: from /home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/capybara-3.28.0/lib/capybara.rb:249:in `run_default_server'
	 8: from /home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/capybara-3.28.0/lib/capybara/registrations/servers.rb:40:in `block in <top (required)>'
	 7: from /home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/capybara-3.28.0/lib/capybara/registrations/servers.rb:40:in `tap'
	 6: from /home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/capybara-3.28.0/lib/capybara/registrations/servers.rb:41:in `block (2 levels) in <top (required)>'
	 5: from /home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/binder.rb:88:in `parse'
	 4: from /home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/binder.rb:88:in `each'
	 3: from /home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/binder.rb:105:in `block in parse'
	 2: from /home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/binder.rb:272:in `add_tcp_listener'
	 1: from /home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/binder.rb:272:in `new'
/home/runner/chopin/vendor/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/binder.rb:272:in `initialize': Address already in use - bind(2) for "127.0.0.1" port 42080 (Errno::EADDRINUSE)
```

## Steps to reproduce
```ruby
require 'socket'

# This is the current code for `find_available_port` in `Capybara::Server` which fails randomly
def find_available_port(host)
  server = TCPServer.new(host, 0)
  server.addr[1]
ensure
  port = server.addr[1]
  server&.close
end

def use_port(host, port)
  server = TCPServer.new(host, port)
ensure
  server&.close
end

count = 0
while true do
  port = find_available_port("0.0.0.0")
  use_port("0.0.0.0", port)
  count += 1
  puts "Port: #{port}: count: #{count}"
end
```

Pull request with fix is at #2244

**Comment by twalpole** [comment]
Please try the issue_2245_port_race branch to see if that fixes the issue you're seeing.  It does reduce the available time for the race condition to occur by holding the TCPServer instance open for as long as possible.

**Comment by twalpole** [comment]
Closing via 156038a08491fd187b45cdf67670688d2f4955a7
