### ISSUE TITLE
Selenium Webdriver "invalid session id" crash after updating to Chrome 78.0.3904.97

### ISSUE THREAD

**Issue by ndbroadbent** [teamcapybara/capybara#2271]
Hello, I'm using the latest version of Chrome on debian stretch (78.0.3904.97). My tests were previously passing on Chrome `78.0.3904.87`.

## Meta

* Capybara Version: `3.29.0`

Driver Information (and browser if relevant):

selenium-webdriver `3.142.6` with Chrome `78.0.3904.97`

## Expected Behavior

No errors

## Actual Behavior

```
      4.1) Failure/Error: click_link 'Sign Up'
345           Selenium::WebDriver::Error::InvalidSessionIdError:
346             invalid session id
347           # #0 0x556f782ce919 <unknown>
348           # ./spec/support/helpers/session_helpers.rb:8:in `sign_up_with'
349           # ****spec.rb:94:in `block (3 levels) in <top (required)>'
350           # ------------------
351           # --- Caused by: ---
352           # Selenium::WebDriver::Error::UnknownError:
353           #   unknown error: session deleted because of page crash
354           #   from unknown error: cannot determine loading status
355           #   from tab crashed
356           #     (Session info: headless chrome=78.0.3904.97)
357           #   #0 0x556f782ce919 <unknown>
358      4.2) Failure/Error: Unable to infer file and line number from backtrace
359           Selenium::WebDriver::Error::InvalidSessionIdError:
360             invalid session id
361           # #0 0x556f782ce919 <unknown>
```

## Steps to reproduce

Hopefully this issue is easy to spot and fix, since all of my feature specs are failing with the same "invalid session id" error. I believe capybara or selenium-webdriver will probably also have some integration tests that should start failing after updating Chrome.

**Comment by twalpole** [comment]
I don't know what `sign_up_with` is doing, but assuming it's standard things that's a bug with Chrome or chromedriver.(did you check for an updated chromedriver to go with the updated Chrome)

**Comment by ndbroadbent** [comment]
Sorry, I forgot to check that, but I updated to the latest chromedriver (78.0.3904.70), and I'm still getting these failures. Some more logs:

```
Failures:
607   1) Static Pages Home Page Visiting the home page
608      Got 0 failures and 2 other errors:
609      1.1) Failure/Error: visit root_url(host: DOMAIN_NAME, port: Capybara.server_port)
610           Selenium::WebDriver::Error::UnknownError:
611             unknown error: session deleted because of page crash
612             from tab crashed
613               (Session info: headless chrome=78.0.3904.97)
614           # #0 0x56221005b919 <unknown>
615           # ******_spec.rb:6:in `block (3 levels) in <top (required)>'
616      1.2) Failure/Error: Unable to infer file and line number from backtrace
617           Selenium::WebDriver::Error::InvalidSessionIdError:
618             invalid session id
619           # #0 0x56221005b919 <unknown>
620   2) Static Pages Home Page Visiting the home page
621      Got 0 failures and 2 other errors:
622      2.1) Failure/Error: visit root_url(host: ADMIN_DOMAIN_NAME, port: Capybara.server_port)
623           Selenium::WebDriver::Error::InvalidSessionIdError:
624             invalid session id
625           # #0 0x56221005b919 <unknown>
626           # ******_spec.rb:20:in `block (3 levels) in <top (required)>'
627      2.2) Failure/Error: Unable to infer file and line number from backtrace
628           Selenium::WebDriver::Error::InvalidSessionIdError:
629             invalid session id
630           # #0 0x56221005b919 <unknown>
631   3) Sign out User signs out successfully
632      Got 0 failures and 2 other errors:
633      3.1) Failure/Error: visit new_user_session_path
634           Selenium::WebDriver::Error::InvalidSessionIdError:
635             invalid session id
636           # #0 0x56221005b919 <unknown>
637           # ./spec/support/helpers/session_helpers.rb:32:in `sign_in_with'
638           # ******_spec.rb:6:in `block (2 levels) in <top (required)>'
639      3.2) Failure/Error: Unable to infer file and line number from backtrace
640           Selenium::WebDriver::Error::InvalidSessionIdError:
641             invalid session id
642           # #0 0x56221005b919 <unknown>
```

And yes `sign_up_with` is just a custom helper method that makes regular Capybara calls to fill in the sign up form, click buttons, etc.

**Comment by twalpole** [comment]
Yeah - there's not much Capybara can do about that - seems to be a chrome issue

**Comment by ndbroadbent** [comment]
Ok yeah, I'll close this but hopefully it will show up in Google results if anyone's looking for it

**Comment by twalpole** [comment]
I wonder if https://news.google.com/articles/CAIiEPvdvAg8iHJYQWStKVgqxNAqFwgEKg4IACoGCAow3O8nMMqOBjCd2ugF?hl=en-US&gl=US&ceid=US%3Aen has anything to do with it

**Comment by ndbroadbent** [comment]
WOW that's crazy! That does sounds like a plausible explanation. Thanks for sharing that!
