### ISSUE TITLE
fill_in partial fills in input fields when animations are present

### ISSUE THREAD

**Issue by brand-it** [teamcapybara/capybara#2280]
## Meta

Capybara Version: 3.29.0
Driver Information: selenium-webdriver 3.12.0 with ChromeDriver 2.40.565383

https://github.com/brand-it/capybara_test

## Expected Behavior

It should fill in the search field with the words "A bunch of gibberish" 

## Actual Behavior

It almost fills in the search with a bunch of gibberish.

```
F  HTML screenshot: tmp/screenshot_2019-11-27-15-39-17.899.html

Failures:

  1) /search fills in the search model input
     Failure/Error: expect(search.value).to eq('A bunch of gibberish')

       expected: "A bunch of gibberish"
            got: "A bunch of gibber"

       (compared using ==)
     # ./spec/app_spec.rb:39:in `block (3 levels) in <top (required)>'
     # ./spec/app_spec.rb:36:in `block (2 levels) in <top (required)>'

Finished in 1.75 seconds (files took 0.50196 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/app_spec.rb:32 # /search fills in the search model input

Failed on try 29
```

## Steps to reproduce

This testing process needs docker but does not require it. You can run selenium but I wanted to make sure I was locked down to the correct version as it is hard to tell if that was the cause. 

1. `git clone git@github.com:brand-it/capybara_test.git`
2. `bundle install`
3. `bin/rspec_custom`

**Comment by brand-it** [comment]
Feel free to close this if it is not an issue with capybara. However, I did not see any good reproducible steps so maybe this will help direct others in the right direction.

**Comment by twalpole** [comment]
This behavior has 2 possible causes -

1. You're using a massively outdated version of chromedriver which has bugs (2.40 was released 18 months ago)

2. A form implemented in a way which can't handle the speed at which Capybara sends keypresses
  This usually happens when the form is configured to send a new request for every keypress (usually when using react, angular, etc) so they can end up with out of order processing of those requests.  The proper solution to that is to add key debounce so multiple requests aren't sent for rapidly entered key presses.

**Comment by twalpole** [comment]
One last thing, you should never write `expect(search.value).to eq('A bunch of gibberish')` instead you should write something like

    expect(page).to have_field('search', with: 'A bunch of gibberish')

so you're using the Capybara provided matchers (which have waiting behavior to handle the asynchronous nature of browsers) rather than the default RSpec matchers which don't.

**Comment by brand-it** [comment]
> You're using a massively outdated version of chromedriver which has bugs (2.40 was released 18 months ago)

I am running the test again using `Chrome Driver 3.5.3`. It looks like that might of fixed it. I have it set up on a loop in that test repo so if it makes it gets success after 200 tries I think that might be the problem. 

I also found a solution with removing the CSS animations however that felt like a hack but I am glad to know that updating the driver fixes the problem. 

> One last thing, you should never write expect(search.value).to eq('A bunch of gibberish') instead, you should write something like...

Ah yeah for this test case I should have switched it out for a `have_field`. The test in the app I am working on is using `expect(page).to have_content('No Results Found')`. Does this test wait, I believe it does but could you(@twalpole) verify that for me?

**Comment by brand-it** [comment]
The solution was to update Chrome Driver from 2.40.565383 to 3.5.3.

**Comment by brand-it** [comment]
Whoops closed this a bit soon. I update the Chrome Driver 3.5.3 and still got the failure.

```
Failures:

  1) /search fills in the search model input
     Failure/Error: expect(search.value).to eq('A bunch of gibberish')

       expected: "A bunch of gibberish"
            got: "A"

       (compared using ==)
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-support-3.8.2/lib/rspec/support.rb:97:in `block in <module:Support>'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-support-3.8.2/lib/rspec/support.rb:106:in `notify_failure'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.4/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.4/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.4/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.4/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.4/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.4/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/app_spec.rb:39:in `block (3 levels) in <top (required)>'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/capybara-3.29.0/lib/capybara/session.rb:343:in `within'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/capybara-3.29.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/capybara-3.29.0/lib/capybara/rspec/matcher_proxies.rb:15:in `within'
     # ./spec/app_spec.rb:36:in `block (2 levels) in <top (required)>'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:257:in `instance_exec'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:257:in `block in run'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/hooks.rb:464:in `block in run'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/hooks.rb:464:in `run'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:254:in `run'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:633:in `block in run_examples'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:629:in `map'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:629:in `run_examples'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:595:in `run'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:116:in `block (3 levels) in run_specs'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:116:in `map'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:116:in `block (2 levels) in run_specs'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/configuration.rb:2008:in `with_suite_hooks'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:110:in `run_specs'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:87:in `run'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:71:in `run'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rspec-core-3.8.2/exe/rspec:4:in `<top (required)>'
     # /Users/blareau/.rbenv/versions/2.6.3/bin/rspec:23:in `load'
     # /Users/blareau/.rbenv/versions/2.6.3/bin/rspec:23:in `<top (required)>'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
     # /Users/blareau/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
     # /Users/blareau/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
     # /Users/blareau/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'

Finished in 8.43 seconds (files took 1.38 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/app_spec.rb:32 # /search fills in the search model input

Failed on try 408
```

**Comment by twalpole** [comment]
@brand-it Yes `have_content` has waiting behavior (it's a Capybara provided matcher).  

Note - I don't know how you disabled your animation, but disabling animations in test mode is generally a good idea since it can speed up the tests and prevent some flaky behaviors - if it's not easy to do in your app and you are letting Capybara run the app under test then Capybara will try and disable animations if you specify `Capybara.disable_animation = true` when configuring capybara.

**Comment by brand-it** [comment]
> disabled your animation,

Based on that recommendation I think that might be what I go with.

**Comment by twalpole** [comment]
I have no clue what Chrome Driver 3.5.3 is - the latest stable version of chromedriver (for use with the latest stable chrome) is 78.0.3904.105 - https://chromedriver.chromium.org/ - anyway all Capybara is doing is sending the keypresses - this isn't a capybara issue

**Comment by brand-it** [comment]
@twalpole OK so it is failing to input the values for the field. Is the issue then with chromedriver?

**Comment by brand-it** [comment]
OH right sorry the docker image we use makes getting the versions confusing for me after digging into the Docker containers it is running `78.0.3904.70`. My bad
