### ISSUE TITLE
Element Click Intercepted Error when executing set_content_editable

### ISSUE THREAD

**Issue by matiasgarcia** [teamcapybara/capybara#2297]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 3.30
Headless Chrome Version: 76.0.3809.100
Chromedriver Version: 76.0.3809.126
React-Select Version: 2.4.4

## Expected Behavior
Not execute content editable maybe?

## Actual Behavior
```
Selenium::WebDriver::Error::ElementClickInterceptedError: element click intercepted: Element <div class="react-select__input" style="display: inline-block;">...</div> is not clickable at point (108, 298). Other element would receive the click: <div class="css-dvua67-singleValue react-select__single-value">...</div>
  (Session info: headless chrome=76.0.3809.100)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Linux 5.0.0-37-generic x86_64)

  0) Currency Balance Sheets Listing filtering allows to filter by client
     Failure/Error: find('.react-select__input', match: :first).set label # set the value

     Selenium::WebDriver::Error::ElementClickInterceptedError:
       element click intercepted: Element <div class="react-select__input" style="display: inline-block;">...</div> is not clickable at point (108, 298). Other element would receive the click: <div class="css-dvua67-singleValue react-select__single-value">...</div>
         (Session info: headless chrome=76.0.3809.100)
         (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Linux 5.0.0-37-generic x86_64)

# /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/capybara-3.30.0/lib/capybara/selenium/nodes/chrome_node.rb:46:in `rescue in click'
# /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/capybara-3.30.0/lib/capybara/selenium/nodes/chrome_node.rb:39:in `click'
# /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/capybara-3.30.0/lib/capybara/selenium/node.rb:337:in `set_content_editable'
# /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/capybara-3.30.0/lib/capybara/selenium/node.rb:87:in `set'
# /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/capybara-3.30.0/lib/capybara/node/element.rb:121:in `block in set'
# /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/capybara-3.30.0/lib/capybara/node/base.rb:83:in `synchronize'
# /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/capybara-3.30.0/lib/capybara/node/element.rb:121:in `set'
# ./spec/pages/react_select.rb:16:in `block in react_select'
# /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/capybara-3.30.0/lib/capybara/session.rb:345:in `within'
# /home/matias/.rvm/gems/ruby-2.5.7@foo/gems/capybara-3.30.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
# ./spec/pages/react_select.rb:12:in `react_select'

 ```

## Steps to reproduce
Capybara code:
```
# frozen_string_literal: true

# Extracted from https://github.com/JedWatson/react-select/issues/832#issuecomment-276441836
module ReactSelect
  REACT_SELECT_CONTROL_CLASS = '.react-select__control'
  REACT_SELECT_MENU_CLASS = '.react-select__menu'
  REACT_SELECT_OPTION_CLASS = '.react-select__option'
  REACT_SELECT_SELECTED_VALUE_CLASS = '.react-select__single-value'

  def react_select(selector, label)
    within selector do
      find(REACT_SELECT_CONTROL_CLASS).click
      return unless has_selector?(REACT_SELECT_MENU_CLASS) # menu should be open now

      find('.react-select__input').set label # set the value
      # This is a little funky because when the entered text forces the select to
      # wrap, it causes React to re-render.  We need to get it to re-render
      # (if needed) by hovering.
      return unless has_selector?(REACT_SELECT_OPTION_CLASS, text: label)

      find(REACT_SELECT_OPTION_CLASS, text: label).hover
      return unless has_selector?(REACT_SELECT_OPTION_CLASS, text: label)

      find(REACT_SELECT_OPTION_CLASS, text: label).click
      return unless has_selector?(REACT_SELECT_SELECTED_VALUE_CLASS, text: label)
    end
  end
end
```

Then call it like this `react_select('.filter-clients', 'Anchorage Capital')`

HTML:

```
<div class="css-1pcexqc-container filter-clients">
    <div class="css-bg1rzq-control react-select__control react-select__control--menu-is-open">
        <div class="css-1hwfws3 react-select__value-container react-select__value-container--has-value">
            <div class="css-dvua67-singleValue react-select__single-value">All clients</div>
            <div class="css-1g6gooi">
                <div class="react-select__input" style="display: inline-block;">
                    <input autocapitalize="none" autocomplete="off" autocorrect="off" id="react-select-2-input" spellcheck="false" tabindex="0" type="text" aria-autocomplete="list" value="" style="box-sizing: content-box; width: 2px; background: 0px center; border: 0px; font-size: inherit; opacity: 1; outline: 0px; padding: 0px; color: inherit;">
                    <div style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: 12px; font-family: Roboto, serif; font-weight: 400; font-style: normal; letter-spacing: normal; text-transform: none;"></div>
                </div>
            </div>
        </div>
        <div class="css-1wy0on6 react-select__indicators"><span class="css-bgvzuu-indicatorSeparator react-select__indicator-separator"></span>
            <div aria-hidden="true" class="css-16pqwjk-indicatorContainer react-select__indicator react-select__dropdown-indicator">
                <svg height="20" width="20" viewBox="0 0 20 20" aria-hidden="true" focusable="false" class="css-19bqh2r">
                    <path d="M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z"></path>
                </svg>
            </div>
        </div>
    </div>
    <div class="css-kj6f9i-menu react-select__menu">
        <div class="css-11unzgr react-select__menu-list">
            <div class="css-xo7z33-option react-select__option react-select__option--is-selected" id="react-select-2-option-0" tabindex="-1">All clients</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-1" tabindex="-1">(24) Anchorage Capital</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-2" tabindex="-1">(8) Arcus Investment Limited</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-3" tabindex="-1">(19) Asset Management Exchange ICAV </div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-4" tabindex="-1">(16) CG Asset Management</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-5" tabindex="-1">(5) City Financial</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-6" tabindex="-1">(9) Dela</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-7" tabindex="-1">(7) Diamond Capital Group</div>
            <div class="css-dpec0i-option react-select__option react-select__option--is-focused" id="react-select-2-option-8" tabindex="-1">(26) Edinburgh Partners</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-9" tabindex="-1">(3) Gerhold LLC Asset Management</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-10" tabindex="-1">(6) GVQ</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-11" tabindex="-1">(17) Harding Loevner LP</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-12" tabindex="-1">(18) Hermes Investment Management</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-13" tabindex="-1">(21) HSBC GAM Canada</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-14" tabindex="-1">(15) Mercer</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-15" tabindex="-1">(12) PPF</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-16" tabindex="-1">(11) SOP</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-17" tabindex="-1">(20) Stichting Instituut Gak</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-18" tabindex="-1">(10) The CoE Pensions Board</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-19" tabindex="-1">(23) The Nuffield Foundation</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-20" tabindex="-1">(13) Unilever</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-21" tabindex="-1">(25) VULCAN VALUE PARTNERS</div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-22" tabindex="-1">(22) Willis Towers Watson </div>
            <div class="css-fk865s-option react-select__option" id="react-select-2-option-23" tabindex="-1">(14) Woodford Asset Management</div>
        </div>
    </div>
</div>
```

![Captura de pantalla de 2020-01-20 12-08-44](https://user-images.githubusercontent.com/2261869/72737135-bf05ca80-3b7d-11ea-8d3c-eb1be50a0f43.png)
![Captura de pantalla de 2020-01-20 12-08-27](https://user-images.githubusercontent.com/2261869/72737137-bf05ca80-3b7d-11ea-8ea7-e551a94e8db3.png)

My thoughts: 
The problem seems to be on this change since `set_content_editable` seems to not be executed in earlier versions of Capybara: https://github.com/teamcapybara/capybara/commit/72ec06b0c49cb68bf2003772110e9c72d301e5bc#diff-fb16fee9bbe627f8524ec725b8a74363L81

**Comment by twalpole** [comment]
The element with class react-select__input is a `div` not an HTML field. The only type of div a user can interact with (set a value of) is a content editable div, so that’s what `set` attempts. It seems you’re really trying to change the value of the `input` element inside the div rather than the div itself.  Assuming the contained input is visible/interactable then you could do that with

    find(‘. react-select__input’).fill_in ‘new value’

or

    find('. react-select__input input’).set ‘new value’

**Comment by matiasgarcia** [comment]
@twalpole Thanks for your quick response, you are absolutely right. I am surprised it worked on earlier versions of Capybara, so definitely it was a bug! Thanks :D
