### ISSUE TITLE
Test failures and pending tests against Ruby2.5

### ISSUE THREAD

**Issue by utkarsh2102** [teamcapybara/capybara#2317]
Hi,

Thank you for your awesome work on capybara so far!
However, while building against Ruby2.5 (with rack > 2), I got a few pending tests and a few failures; here are they:
```
Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Capybara.string drops illegal fragments when using gumbo
     # libxml is less strict than Gumbo
     # ./spec/basic_node_spec.rb:113

  2) Capybara.string can disable use of gumbo
     # Test doesn't make sense unlesss nokogumbo is loaded
     # ./spec/basic_node_spec.rb:118

  3) Capybara::Session DSL #has_css? should support case insensitive :class and :id options
     # Nokogiri doesn't support case insensitive CSS attribute matchers
     Failure/Error: raise ArgumentError, "This driver doesn't support case insensitive attribute matching when using CSS base selectors"

     ArgumentError:
       This driver doesn't support case insensitive attribute matching when using CSS base selectors
     # ./lib/capybara/rack_test/driver.rb:81:in `rescue in find_css'
     # ./lib/capybara/rack_test/driver.rb:76:in `find_css'
     # ./lib/capybara/node/base.rb:109:in `find_css'
     # ./lib/capybara/queries/selector_query.rb:238:in `find_nodes_by_selector_format'
     # ./lib/capybara/queries/selector_query.rb:154:in `block in resolve_for'
     # ./lib/capybara/node/base.rb:77:in `synchronize'
     # ./lib/capybara/queries/selector_query.rb:153:in `resolve_for'
     # ./lib/capybara/node/matchers.rb:844:in `block in _verify_selector_result'
     # ./lib/capybara/node/base.rb:83:in `synchronize'
     # ./lib/capybara/node/matchers.rb:843:in `_verify_selector_result'
     # ./lib/capybara/node/matchers.rb:109:in `assert_selector'
     # ./lib/capybara/session.rb:759:in `block (2 levels) in <class:Session>'
     # ./lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
     # ./lib/capybara/rspec/matchers/have_selector.rb:18:in `element_matches?'
     # ./lib/capybara/rspec/matchers/base.rb:51:in `matches?'
     # ./lib/capybara/spec/session/has_css_spec.rb:69:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Nokogiri::CSS::SyntaxError:
     #   unexpected ' ' after '[:substring_match, "'UITARI'"]'
     #   ./lib/capybara/rack_test/browser.rb:104:in `find'

  4) Capybara::DSL#current_session should change with the current driver
     # waiting to have ruby-capybara-webkit or ruby-selenium-driver in Debian
     Failure/Error: if Gem.loaded_specs['selenium-webdriver'].version < Gem::Version.new('3.5.0')

     NoMethodError:
       undefined method `version' for nil:NilClass
     # ./lib/capybara/selenium/driver.rb:23:in `load_selenium'
     # ./lib/capybara/selenium/driver.rb:60:in `initialize'
     # ./lib/capybara/registrations/drivers.rb:8:in `new'
     # ./lib/capybara/registrations/drivers.rb:8:in `block in <top (required)>'
     # ./lib/capybara/session.rb:104:in `driver'
     # ./lib/capybara/session.rb:90:in `initialize'
     # ./lib/capybara.rb:415:in `new'
     # ./lib/capybara.rb:415:in `block in session_pool'
     # ./lib/capybara.rb:312:in `current_session'
     # ./spec/dsl_spec.rb:165:in `block (3 levels) in <top (required)>'

  5) Capybara::DSL#current_session should be persistent even across driver changes
     # waiting to have ruby-capybara-webkit or ruby-selenium-driver in Debian
     Failure/Error: if Gem.loaded_specs['selenium-webdriver'].version < Gem::Version.new('3.5.0')

     NoMethodError:
       undefined method `version' for nil:NilClass
     # ./lib/capybara/selenium/driver.rb:23:in `load_selenium'
     # ./lib/capybara/selenium/driver.rb:60:in `initialize'
     # ./lib/capybara/registrations/drivers.rb:8:in `new'
     # ./lib/capybara/registrations/drivers.rb:8:in `block in <top (required)>'
     # ./lib/capybara/session.rb:104:in `driver'
     # ./lib/capybara/session.rb:90:in `initialize'
     # ./lib/capybara.rb:415:in `new'
     # ./lib/capybara.rb:415:in `block in session_pool'
     # ./lib/capybara.rb:312:in `current_session'
     # ./spec/dsl_spec.rb:173:in `block (3 levels) in <top (required)>'

  6) Capybara::Session RackTest #has_css? should support case insensitive :class and :id options
     # Nokogiri doesn't support case insensitive CSS attribute matchers
     # ./lib/capybara/spec/session/has_css_spec.rb:68

  7) Capybara::String should use gumbo
     # Only  valid if gumbo is included
     # ./spec/rack_test_spec.rb:236

  8) if xfeature aliases to pending then this should be 'temporarily disabled with xfeature'
     # Temporarily disabled with xfeature
     # ./spec/rspec/features_spec.rb:81

  9) if xfeature aliases to pending then this also should be 'temporarily disabled with xfeature'
     # Temporarily disabled with xfeature
     # ./spec/rspec/features_spec.rb:85

  10) if xscenario aliases to pending then this test should be 'temporarily disabled with xscenario'
     # Temporarily disabled with xscenario
     # ./spec/rspec/scenarios_spec.rb:17

  11) Capybara::Server should support SSL
     # Temporarily skipped with xit
     # ./spec/server_spec.rb:106

Failures:

  1) Capybara::Session DSL #click_button should follow permanent redirects that maintain method
     Failure/Error: pending "Rack < 2 doesn't support 308" if Gem.loaded_specs['rack'].version < Gem::Version.new('2.0.0')

     NoMethodError:
       undefined method `version' for nil:NilClass
     # ./spec/dsl_spec.rb:17:in `block in <top (required)>'
     # ./lib/capybara/spec/spec_helper.rb:66:in `instance_exec'
     # ./lib/capybara/spec/spec_helper.rb:66:in `block (2 levels) in run_specs'

  2) Capybara::Session RackTest #click_button should follow permanent redirects that maintain method
     Failure/Error: skip "Rack < 2 doesn't support 308" if Gem.loaded_specs['rack'].version < Gem::Version.new('2.0.0')

     NoMethodError:
       undefined method `version' for nil:NilClass
     # ./spec/rack_test_spec.rb:35:in `block in <top (required)>'
     # ./lib/capybara/spec/spec_helper.rb:66:in `instance_exec'
     # ./lib/capybara/spec/spec_helper.rb:66:in `block (2 levels) in run_specs'

Finished in 2 minutes 58.2 seconds (files took 1.31 seconds to load)
2454 examples, 2 failures, 11 pending

Failed examples:

rspec './lib/capybara/spec/spec_helper.rb[1:108:32]' # Capybara::Session DSL #click_button should follow permanent redirects that maintain method
rspec './lib/capybara/spec/spec_helper.rb[2:108:32]' # Capybara::Session RackTest #click_button should follow permanent redirects that maintain method

/usr/bin/ruby2.5 -I/usr/share/rubygems-integration/all/gems/rspec-support-3.9.2/lib:/usr/share/rubygems-integration/all/gems/rspec-core-3.9.1/lib /usr/share/rubygems-integration/all/gems/rspec-core-3.9.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
ERROR: Test "ruby2.5" failed. Exiting.
````

Could you please take a look and help us figure out this?

**Comment by twalpole** [comment]
Capybara works fine with the latest version of `rack` - https://travis-ci.org/teamcapybara/capybara/jobs/653770201

Pending tests are expected due to specific configurations, and I have no idea why you’re seeing failures on 2 tests because I don’t know what you’re actually doing. From the errors it looks like you’re running rack_test tests without having rack installed at all

**Comment by twalpole** [comment]
Closing since this some of the pending test messages aren't even from Capybara, so I'm assuming you're running a patched version of Capybara??? which I definitely can't support.
