### ISSUE TITLE
Se4 - Remote - Firefox: Creating driver throws private method error on driver specialization

### ISSUE THREAD

**Issue by luke-hill** [teamcapybara/capybara#2380]
## Meta
Capybara Version: `3.29.0`
Driver Information (and browser if relevant): selenium-webdriver `4.0.alpha6` with Firefox `77` #Works fine on Selenium3.14 with everything else identical

## Expected Behavior
A driver can be instantiated

## Actual Behavior
```
private method `commands' called for #<Selenium::WebDriver::Remote::Bridge:0x0000555e81b80d00> (NoMethodError)
/home/luke/.rvm/gems/ruby-2.6.6/gems/capybara-3.29.0/lib/capybara/selenium/driver_specializations/firefox_driver.rb:9:in `extended'
/home/luke/.rvm/gems/ruby-2.6.6/gems/capybara-3.29.0/lib/capybara/selenium/driver.rb:440:in `extend'
/home/luke/.rvm/gems/ruby-2.6.6/gems/capybara-3.29.0/lib/capybara/selenium/driver.rb:440:in `block in specialize_driver'
/home/luke/.rvm/gems/ruby-2.6.6/gems/capybara-3.29.0/lib/capybara/selenium/driver.rb:439:in `each_value'
/home/luke/.rvm/gems/ruby-2.6.6/gems/capybara-3.29.0/lib/capybara/selenium/driver.rb:439:in `specialize_driver'
/home/luke/.rvm/gems/ruby-2.6.6/gems/capybara-3.29.0/lib/capybara/selenium/driver.rb:51:in `browser'
```
## Steps to reproduce
Standard cucumber project. Driver creation/capabilities are as follows
```
desired_capabilities = 
        {
          "browserName" => "firefox",
          "browserVersion" => "77" # Also on 76/75 this fails
          "bstack:options" => {
            "buildName" => "build_name",
            "projectName" => "projectName",
            "sessionName" => "session",
            "os" => "Windows",
            "osVersion" => "10", # Also on 7 this fails
            "local" => "false",
            "seleniumVersion" => "4.0.0-alpha-6",
            "debug" => "false",
            "consoleLogs" => "verbose",
            "networkLogs" => "false",
            "resolution" => "1920x1080"
          }
        }

options = Selenium::WebDriver::Firefox::Options.new(log_level: "info")

      def register
        Capybara.register_driver :selenium do |app|
          Capybara::Selenium::Driver.new(
            app,
            browser: :remote,
            capabilities: [desired_capabilities, options],
            url: browserstack_hub_url
          )
        end
      end
```

**Comment by luke-hill** [comment]
Altering the line from

   `bridge.extend Capybara::Selenium::IsDisplayed unless bridge.commands(:is_element_displayed)`
to
    `bridge.extend Capybara::Selenium::IsDisplayed unless bridge.send(:commands, :is_element_displayed)`

Seems to make it work. Obviously this overrides any protections in-place.

**Comment by luke-hill** [comment]
Update

The reason this isn't required in chromedriver, is because you extend chromedriver with chromelogs patch, which then makes commands public. Is there something you'd prefer me to do here? I can land a patch if it'll be accepted but not sure which way you want to do it.
