### ISSUE TITLE
Capybara doesn't handle unexpectedly open alert dialogs in Chrome 85

### ISSUE THREAD

**Issue by agrobbin** [teamcapybara/capybara#2382]
## Meta
Capybara Version:
3.33.0
Driver Information (and browser if relevant):
Chrome 85.0.4183.76
ChromeDriver 85.0.4183.38

## Expected Behavior
Capybara should gracefully reset the browser even if there is an open alert dialog on Chrome 85.

## Actual Behavior
An `EOFError` exception is raised, that is not gracefully `rescue`d like `Selenium::WebDriver::Error::UnexpectedAlertOpenError`.

## Steps to reproduce

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'capybara'
  gem 'puma'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'byebug'
end

require 'selenium-webdriver'
require 'capybara/dsl'

html = <<~HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello World</title>
    <meta charset="utf-8">

    <script type="text/javascript">
      window.addEventListener('beforeunload', (event) => {
        event.preventDefault();
        event.returnValue = '';
      });
    </script>
  </head>
  <body>
    <h1><a href="#">Hello World</a></h1>
  </body>
</html>
HTML

app = proc { |env| [200, { "Content-Type" => "text/html" }, [html] ] }

session = Capybara::Session.new(:selenium_chrome, app)
session.visit '/'
session.click_on 'Hello World' # interact with the page, to get Chrome to fire `beforeunload`
session.reset!
```

This is the minimally reproducible test case I could come up with. On Chrome 84, this test case raises an `Selenium::WebDriver::Error::UnexpectedAlertOpenError`, while on Chrome 85, it raises `EOFError`:

```
Traceback (most recent call last):
	18: from capybara_chrome_85_alert.rb:40:in `<main>'
	17: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/capybara-3.32.1/lib/capybara/session.rb:130:in `reset!'
	16: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/capybara-3.32.1/lib/capybara/selenium/driver_specializations/chrome_driver.rb:49:in `reset!'
	15: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/navigation.rb:32:in `to'
	14: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:59:in `get'
	13: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
	12: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
	11: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
	10: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:82:in `request'
	 9: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:129:in `response_for'
	 8: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1492:in `request'
	 7: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
	 6: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
	 5: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
	 4: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
	 3: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
	 2: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
	 1: from /usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/2.7.0/net/protocol.rb:225:in `rbuf_fill': end of file reached (EOFError)
```

 Happy to help investigate this further, and/or direct this somewhere else if Capybara is not the appropriate place for this issue!

**Comment by shelmire** [comment]
@agrobbin Thanks for reporting this issue in all the relevant places; it's breaking for my company's test suite as well on Chrome 85 (though with a different cause, the problem is ultimately the browser not being reset).

**Comment by agrobbin** [comment]
@shelmire my pleasure! [ChromeDriver Issue 3578](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3578) has already been fixed, and should be released soon!

**Comment by radar** [comment]
One small amendment to this reproduction script:

```
Webdrivers::Chromedriver.required_version = '85.0.4183.83'
```

Is required now after `require "capybara/dsl"`, this will ensure that it's using the broken version of Chromedriver, not the latest (which is now 85.0.4183.87, and contains the fix for ChromeDriver Issue 3578.

**Comment by radar** [comment]
I'm about to get a slightly different error message, but still reproduce the same issue with this script:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'capybara'
  gem 'puma'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'byebug'
  gem 'pry'
end

require 'selenium-webdriver'
require 'capybara/dsl'

Webdrivers::Chromedriver.required_version = '85.0.4183.83'
Selenium::WebDriver.logger.level = Logger::DEBUG

html = <<~HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello World</title>
    <meta charset="utf-8">

    <script type="text/javascript">
      window.addEventListener('beforeunload', (event) => {
        event.preventDefault();
        event.returnValue = '';
      });
    </script>
  </head>
  <body>
    <h1><a href="https://google.com">Hello World</a></h1>
  </body>
</html>
HTML

app = proc { |env| [200, { "Content-Type" => "text/html" }, [html] ] }

session = Capybara::Session.new(:selenium_chrome, app)
session.visit '/'
binding.pry
session.click_on 'Hello World' # interact with the page, to get Chrome to fire `beforeunload`

session.visit '/'
```

Here's what I see:

```
2020-08-30 08:39:15 INFO Selenium <- {"value":{"data":{"text":"{Alert text : "},"error":"unexpected alert open","message":"unexpected alert open: {Alert text : }\n  (Session info: chrome=85.0.4183.83)","stacktrace":"0   chromedriver                        0x000000010a9261b9 chromedriver + 4911545\n1   chromedriver                        0x000000010a8c5e03 chromedriver + 4517379\n2   chromedriver                        0x000000010a533da6 chromedriver + 773542\n3   chromedriver                        0x000000010a4c4072 chromedriver + 315506\n4   chromedriver                        0x000000010a4b7c23 chromedriver + 265251\n5   chromedriver                        0x000000010a491720 chromedriver + 108320\n6   chromedriver                        0x000000010a492693 chromedriver + 112275\n7   chromedriver                        0x000000010a8eef72 chromedriver + 4685682\n8   chromedriver                        0x000000010a8fcb3a chromedriver + 4741946\n9   chromedriver                        0x000000010a8fc801 chromedriver + 4741121\n10  chromedriver                        0x000000010a8d225e chromedriver + 4567646\n11  chromedriver                        0x000000010a8fd061 chromedriver + 4743265\n12  chromedriver                        0x000000010a8e3d0a chromedriver + 4640010\n13  chromedriver                        0x000000010a9160ba chromedriver + 4845754\n14  chromedriver                        0x000000010a92c387 chromedriver + 4936583\n15  libsystem_pthread.dylib             0x00007fff67652109 _pthread_start + 148\n16  libsystem_pthread.dylib             0x00007fff6764db8b thread_start + 15\n"}}
2020-08-30 08:39:15 INFO Selenium -> DELETE session/98dc99cdb8251a265b3d80bf3e386d80
2020-08-30 08:39:15 INFO Selenium <- {"value":null}
Traceback (most recent call last):
	29: from capybara-2382.rb:46:in `<main>'
	28: from /Users/ryanbigg/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/capybara-3.33.0/lib/capybara/session.rb:278:in `visit'
	27: from /Users/ryanbigg/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/capybara-3.33.0/lib/capybara/selenium/driver.rb:71:in `visit'
	26: from /Users/ryanbigg/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/navigation.rb:32:in `to'
	25: from /Users/ryanbigg/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:59:in `get'
	24: from /Users/ryanbigg/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
	23: from /Users/ryanbigg/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
	22: from /Users/ryanbigg/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
	21: from /Users/ryanbigg/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
	20: from /Users/ryanbigg/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
	19: from /Users/ryanbigg/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
	18: from /Users/ryanbigg/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	17: from /Users/ryanbigg/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
	16: from 16  libsystem_pthread.dylib             0x00007fff6764db8b thread_start + 15
	15: from 15  libsystem_pthread.dylib             0x00007fff67652109 _pthread_start + 148
	14: from 14  chromedriver                        0x000000010a92c387 chromedriver + 4936583
	13: from 13  chromedriver                        0x000000010a9160ba chromedriver + 4845754
	12: from 12  chromedriver                        0x000000010a8e3d0a chromedriver + 4640010
	11: from 11  chromedriver                        0x000000010a8fd061 chromedriver + 4743265
	10: from 10  chromedriver                        0x000000010a8d225e chromedriver + 4567646
	 9: from 9   chromedriver                        0x000000010a8fc801 chromedriver + 4741121
	 8: from 8   chromedriver                        0x000000010a8fcb3a chromedriver + 4741946
	 7: from 7   chromedriver                        0x000000010a8eef72 chromedriver + 4685682
	 6: from 6   chromedriver                        0x000000010a492693 chromedriver + 112275
	 5: from 5   chromedriver                        0x000000010a491720 chromedriver + 108320
	 4: from 4   chromedriver                        0x000000010a4b7c23 chromedriver + 265251
	 3: from 3   chromedriver                        0x000000010a4c4072 chromedriver + 315506
	 2: from 2   chromedriver                        0x000000010a533da6 chromedriver + 773542
	 1: from 1   chromedriver                        0x000000010a8c5e03 chromedriver + 4517379
0   chromedriver                        0x000000010a9261b9 chromedriver + 4911545: unexpected alert open: {Alert text : } (Selenium::WebDriver::Error::UnexpectedAlertOpenError)
```
