### ISSUE TITLE
Puma 5.0.1 gives `undefined method `min_threads=' for #<Puma::Server> (NoMethodError)` on server boot

### ISSUE THREAD

**Issue by nertzy** [teamcapybara/capybara#2397]
## Meta
Capybara Version: 3.33.0

Driver Information (and browser if relevant):
- puma 5.0.1 (released today)
- webdrivers 4.4.1
- selenium-webdriver 3.142.7
- ChromeDriver 85.0.4183.87
- Google Chrome 85.0.4183.121 (headless)

## Expected Behavior

Server boots and tests are run.

## Actual Behavior

```
/Users/dev/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-5.0.1/lib/puma/server.rb:87: warning: deprecated Object#=~ is called on Proc; it always returns
 nil
#<Thread:0x00007f97548d5778 /Users/dev/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/capybara-3.33.0/lib/capybara/server.rb:76 run> terminated with exception
 (report_on_exception is true):
Traceback (most recent call last):
        4: from /Users/dev/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/capybara-3.33.0/lib/capybara/server.rb:77:in `block in boot'
        3: from /Users/dev/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/capybara-3.33.0/lib/capybara/config.rb:64:in `block in server='
        2: from /Users/dev/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/capybara-3.33.0/lib/capybara/registrations/servers.rb:40:in `block in <main>'
        1: from /Users/dev/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/capybara-3.33.0/lib/capybara/registrations/servers.rb:40:in `tap'
/Users/dev/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/capybara-3.33.0/lib/capybara/registrations/servers.rb:42:in `block (2 levels) in <main>': undefined
method `min_threads=' for #<Puma::Server:0x00007f9755b5c658> (NoMethodError)
Did you mean?  min_threads
               max_threads
```

## Steps to reproduce
- Upgrade puma to 5.0.1
- Run `rails spec:system` in a Rails app with system specs that use Capybara

**Comment by nateberkopec** [comment]
Sorry folks, this was our bad. Please use 5.0.2.

**Comment by nertzy** [comment]
Puma 5.0.2 fixes the issue for me. Thanks @nateberkopec!

**Comment by nateberkopec** [comment]
Thanks for the fast report @nertzy, it allowed me to fix it quickly 👍
