### ISSUE TITLE
Exit status causes specs to fail after upgrading to ruby 3

### ISSUE THREAD

**Issue by lvonk** [teamcapybara/capybara#2449]
Hi we are upgrading our app to ruby 3.0 and updating our gems accordingly.

We are experiencing an issue with running our Capybara specs in that when it is done it fails when shutting down selenium because the exit code is not 0. This happens sometimes, not for all tests by the way. See stacktrace below.

## Meta
- ruby 3.0 (via circleci image `cimg/ruby:3.0.0`)
- `capybara (3.35.3)`
- `selenium-webdriver (4.0.0.alpha7)`
- `webdrivers (4.5.0)`
- `rspec (3.10.0)`
- `selenium/standalone-chrome:4.0.0`

## Expected Behavior

It ignores any shutdown errors and returns the correct exit code (0)

## Actual Behavior
To be able to handle https://github.com/SeleniumHQ/selenium/issues/9130 we patched the `Selenium::WebDriver::Remote::Http::Common.create_response` to be able to handle empty `content_type`. That's why you see `/home/circleci/repo/spec/ext/common.rb:30` in the stacktrace, which is a copy of `Selenium::WebDriver::Remote::Http::Common`.

```ruby
Finished in 6 minutes 10 seconds (files took 5.93 seconds to load)
260 examples, 0 failures

/home/circleci/repo/spec/ext/common.rb:30:in `create_response': unexpected response, code=404, content-type="" (Selenium::WebDriver::Error::WebDriverError)
Unable to route (DELETE) /session/ee3cb3f3f939848e104befaf7bc337b4
	from /home/circleci/repo/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.0.0.alpha7/lib/selenium/webdriver/remote/http/default.rb:110:in `request'
	from /home/circleci/repo/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.0.0.alpha7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
	from /home/circleci/repo/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.0.0.alpha7/lib/selenium/webdriver/remote/bridge.rb:567:in `execute'
	from /home/circleci/repo/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.0.0.alpha7/lib/selenium/webdriver/remote/bridge.rb:178:in `quit'
	from /home/circleci/repo/vendor/bundle/ruby/3.0.0/gems/selenium-webdriver-4.0.0.alpha7/lib/selenium/webdriver/common/driver.rb:172:in `quit'
	from /home/circleci/repo/vendor/bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/selenium/driver.rb:282:in `quit'
	from /home/circleci/repo/vendor/bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/selenium/driver.rb:502:in `block in setup_exit_handler'
Ignoring Selenium UnknownError during driver quit: org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: 8e671805ccb441410ecb8f7085f1040b
Build info: version: '4.0.0-beta-1', revision: '6eecd00e79'
System info: host: 'a4d5393ae323', ip: '172.30.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1092-aws', java.version: '1.8.0_275'
Driver info: driver.version: unknown
Ignoring Selenium UnknownError during driver quit: org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: 43c400c78919062db1b08a3e3f82edba
Build info: version: '4.0.0-beta-1', revision: '6eecd00e79'
System info: host: 'a4d5393ae323', ip: '172.30.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1092-aws', java.version: '1.8.0_275'
Driver info: driver.version: unknown
Ignoring Selenium UnknownError during driver quit: org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: 80256538d43b839f8812932178833461
Build info: version: '4.0.0-beta-1', revision: '6eecd00e79'
System info: host: 'a4d5393ae323', ip: '172.30.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1092-aws', java.version: '1.8.0_275'
Driver info: driver.version: unknown
Coverage report generated for RSpec 17 to /home/circleci/repo/coverage. 34500 / 49238 LOC (70.07%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected

Exited with code exit status 123
CircleCI received exit code 123
```

**Comment by twalpole** [comment]
Not sure what you want Capybara to do about this, seems like a Selenium bug - or incompatibility between the selenium-webdriver 4.0.0.alpha7 and 4.0.0.beta1 container you appear to be running

**Comment by lvonk** [comment]
Hi @twalpole I thought since there is already some code in place that ignores errors on `quit` in `Capybara::Selenium::Driver` perhaps this might be worth adding. If not, feel free to close and this might serve as a reference for others experiencing the same error.

**Comment by titusfortner** [comment]
This can be closed. It was addressed here: https://github.com/SeleniumHQ/selenium/issues/9130
