### ISSUE TITLE
has_selector segfaults with Nokogiri 1.11.4+

### ISSUE THREAD

**Issue by cbeer** [teamcapybara/capybara#2466]
## Meta
Capybara Version: 3.35.3
Nokogiri: 1.11.4 or greater; 1.11.3 works fine.

## Expected Behavior

Before Nokogiri 1.11.4, I could initialize `Capybara::Node::Simple` with an existing Nokogiri HTML element, and `node#has_selector?` should not segfault when called with a CSS selector that isn't in the DOM

## Actual Behavior

I consistently get this segfault (on Ruby 2.7 + 3.0):

```
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/simple.rb:71: [BUG] Segmentation fault at 0x0000000000000000
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0018 p:---- s:0093 e:000092 CFUNC  :path
c:0017 p:0005 s:0089 e:000088 METHOD ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/simple.rb:71
c:0016 p:0032 s:0085 e:000084 METHOD ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/queries/selector_query.rb:418
c:0015 p:0025 s:0080 e:000079 METHOD ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/queries/selector_query.rb:410
c:0014 p:0460 s:0076 e:000075 METHOD ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/queries/selector_query.rb:97
c:0013 p:0005 s:0069 e:000068 METHOD ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/queries/selector_query.rb:106
c:0012 p:0005 s:0065 e:000063 METHOD ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/queries/selector_query.rb:171
c:0011 p:0005 s:0060 e:000059 METHOD ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/result.rb:114
c:0010 p:0039 s:0054 e:000051 BLOCK  ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:112
c:0009 p:0010 s:0047 e:000046 BLOCK  ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:844
c:0008 p:0005 s:0044 e:000043 METHOD ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/simple.rb:156
c:0007 p:0065 s:0039 e:000038 METHOD ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:843
c:0006 p:0009 s:0030 e:000029 METHOD ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:110
c:0005 p:0017 s:0024 e:000023 BLOCK  ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:39
c:0004 p:0025 s:0021 e:000020 METHOD ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:877
c:0003 p:0006 s:0016 e:000015 METHOD ~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:39
c:0002 p:0096 s:0009 E:000358 EVAL   a.rb:21 [FINISH]
c:0001 p:0000 s:0003 E:000280 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
a.rb:21:in `<main>'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:39:in `has_selector?'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:877:in `make_predicate'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:39:in `block in has_selector?'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:110:in `assert_selector'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:843:in `_verify_selector_result'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/simple.rb:156:in `synchronize'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:844:in `block in _verify_selector_result'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/matchers.rb:112:in `block in assert_selector'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/result.rb:114:in `failure_message'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/queries/selector_query.rb:171:in `failure_message'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/queries/selector_query.rb:106:in `applied_description'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/queries/selector_query.rb:97:in `description'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/queries/selector_query.rb:410:in `describe_within?'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/queries/selector_query.rb:418:in `simple_root?'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/simple.rb:71:in `path'
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/capybara-3.35.3/lib/capybara/node/simple.rb:71:in `path'

-- Machine register context ------------------------------------------------
 rax: 0x0000000000000000 rbx: 0x0000000000000000 rcx: 0x0000000000000000
 rdx: 0x0000000000000000 rdi: 0x0000000000000000 rsi: 0x000000005a47c0ae
 rbp: 0x00007ffee3daa2e0 rsp: 0x00007ffee3daa2e0  r8: 0x00000000000086d9
  r9: 0x000000000000003f r10: 0x00007ff4e9400000 r11: 0x0000000000000000
 r12: 0x0000000000000000 r13: 0x0000000055550083 r14: 0x00007ff54fd06770
 r15: 0x00007ff540127c48 rip: 0x00007fff205c1552 rfl: 0x0000000000010246

-- C level backtrace information -------------------------------------------
~/.rbenv/versions/3.0.0/lib/libruby.3.0.dylib(rb_vm_bugreport+0x6cf) [0x10c0ffb9f]
~/.rbenv/versions/3.0.0/lib/libruby.3.0.dylib(rb_bug_for_fatal_signal+0x1d6) [0x10bf18966]
~/.rbenv/versions/3.0.0/lib/libruby.3.0.dylib(sigsegv+0x5b) [0x10c05773b]
/usr/lib/system/libsystem_platform.dylib(_sigtramp+0x1d) [0x7fff205c3d7d]
/usr/lib/system/libsystem_platform.dylib(0x7fff205c1552) [0x7fff205c1552]
```

## Steps to reproduce

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'capybara'
  gem 'nokogiri', '~> 1.11.4'
end

html = <<-HTML
  <div class=""></div>
HTML

fragment = Nokogiri::HTML.fragment(html)

# This is fine
node = Capybara::Node::Simple.new(fragment.to_s)
node.has_selector? '.does-not-exist'

# This segfaults
node = Capybara::Node::Simple.new(fragment)
node.has_selector? '.does-not-exist'
```

**Comment by twalpole** [comment]
First reaction is that this looks like an issue with nokogiri, either in nokogiri or that you've updated some library and need to rebuild nokogiri

**Comment by twalpole** [comment]
Please try nokogiri 1.11.5 https://github.com/sparklemotion/nokogiri/releases/tag/v1.11.5

**Comment by cbeer** [comment]
Thanks. It's still a problem with Nokogiri 1.11.5. I'll try to make a reproducible test case for them 🤷‍♂️
