### ISSUE TITLE
Puma 5.6.2 gives undefined method `strings' for Puma::Events:Class when running tests

### ISSUE THREAD

**Issue by nguyenntph** [teamcapybara/capybara#2529]
## Meta
Capybara Version: 3.36.0 (also try with 3.35.3)

Driver Information (and browser if relevant):
puma 5.6.2
selenium-webdriver 3.142.7

## Expected Behavior
Tests can be run

## Actual Behavior
With slient option
```
/Users/developer/.rvm/gems/ruby-2.7.1/gems/capybara-3.36.0/lib/capybara/server.rb:76 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        2: from /Users/developer/.rvm/gems/ruby-2.7.1/gems/capybara-3.36.0/lib/capybara/server.rb:77:in `block in boot'
        1: from /Users/developer/.rvm/gems/ruby-2.7.1/gems/capybara-3.36.0/lib/capybara/config.rb:64:in `block in server='
/Users/developer/.rvm/gems/ruby-2.7.1/gems/capybara-3.36.0/lib/capybara/registrations/servers.rb:32:in `block in <main>': undefined method `strings' for Puma::Events:Class (NoMethodError)
```
Without silent option
```
/Users/developer/.rvm/gems/ruby-2.7.1/gems/capybara-3.36.0/lib/capybara/server.rb:76 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from /Users/developer/.rvm/gems/ruby-2.7.1/gems/capybara-3.36.0/lib/capybara/server.rb:77:in `block in boot'
/Users/developer/.rvm/gems/ruby-2.7.1/gems/capybara-3.36.0/lib/capybara/registrations/servers.rb:32:in `block in <main>': undefined method `stdio' for Puma::Events:Class (NoMethodError)
```

## Steps to reproduce
Upgrade puma to 5.6.2
Run rspec spec/features in a Rails app that use puma as server, with integration tests that use Capybara

**Comment by twalpole** [comment]
Sorry about the delay on this, been really busy recently - will hopefully have time to look into whatever puma changed later this week.

**Comment by twalpole** [comment]
@nguyenntph Are you sure you're running Puma 5.6.2 ? I'm not seeing the issue you're reporting

```
(byebug) Puma::Const::PUMA_VERSION
"5.6.2"
(byebug) Puma::Events.stdio
#<Puma::Events:0x0000000109eacb08 @formatter=#<Puma::Events::DefaultFormatter:0x0000000109eacae0>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @debug=false, @error_logger=#<Puma::ErrorLogger:0x0000000109eacab8 @ioerr=#<IO:<STDERR>>, @debug=false>, @hooks={}>
(byebug) Puma::Events.strings
#<Puma::Events:0x0000000109eb79b8 @formatter=#<Puma::Events::DefaultFormatter:0x0000000109eb7990>, @stdout=#<StringIO:0x0000000109eb7a58>, @stderr=#<StringIO:0x0000000109eb7a08>, @debug=false, @error_logger=#<Puma::ErrorLogger:0x0000000109eb7968 @ioerr=#<StringIO:0x0000000109eb7a08>, @debug=false>, @hooks={}>
```

**Comment by twalpole** [comment]
@nguyenntph You're not running 5.6.2 - you're running master branch of `puma` --  We can't support a WIP version of Puma which is undergoing changes to parameters required to initialize classes, etc.  You'll need to register your own server.

**Comment by elalemanyo** [comment]
A [new Puma version](https://github.com/puma/puma/blob/master/6.0-Upgrade.md) has just been released, the problem with `Puma::Events.stdio` and `Puma::Events.strings` is now real 😔
