### ISSUE TITLE
"undefined method 'log'" for `page.driver.browser.manage.logs.get(:browser)` with Firefox

### ISSUE THREAD

**Issue by UweKubosch** [teamcapybara/capybara#2561]
## Meta
Capybara Version:  3.37.1
selenium-webdriver (4.2.1)
Firefox 101.0

## Expected Behavior

Calling `page.driver.browser.manage.logs.get(:browser)` returns the browser console log.

## Actual Behavior

```
Minitest::UnexpectedError: NoMethodError: undefined method `log' for #<Selenium::WebDriver::Remote::Bridge:0x0000000113894018...>

        @bridge.log type
               ^^^^
    selenium-webdriver (4.2.1) lib/selenium/webdriver/common/logs.rb:32:in `get'
    test/application_system_test_case.rb:53:in `block in <class:ApplicationSystemTestCase>'
```

## Steps to reproduce

Configure Firefox:

```ruby
class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :headless_firefox
  teardown do
    puts page.driver.browser.manage.logs.get(:browser).map(&:message).join("\n")
  end
end
```

**Comment by twalpole** [comment]
When you call `page.driver.browser` you're interacting directly with the driver, in your case selenium.  This has nothing to do with Capybara
