### ISSUE TITLE
Undefined method `text` for shadow root

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2588]
## Meta
Capybara Version:
3.37.1
Driver Information (and browser if relevant):
Selenium 4.4.0 on Chrome 106

## Expected Behavior
No exception

## Actual Behavior
Exception:

```
     Failure/Error: expect(find('div').shadow_root).to have_text('some text')

     NoMethodError:
       undefined method `text' for #<Selenium::WebDriver::ShadowRoot:0x25fbe3bf>
       Did you mean?  test
     # ./build/.gems/gems/capybara-3.37.1/lib/capybara/selenium/node.rb:13:in `visible_text'
     # ./build/.gems/gems/capybara-3.37.1/lib/capybara/node/element.rb:60:in `block in text'
     # ./build/.gems/gems/capybara-3.37.1/lib/capybara/node/base.rb:77:in `synchronize'
     # ./build/.gems/gems/capybara-3.37.1/lib/capybara/node/element.rb:60:in `text'
     # ./build/.gems/gems/capybara-3.37.1/lib/capybara/queries/text_query.rb:108:in `text'
     # ./build/.gems/gems/capybara-3.37.1/lib/capybara/queries/text_query.rb:29:in `resolve_for'
     # ./build/.gems/gems/capybara-3.37.1/lib/capybara/node/matchers.rb:862:in `block in _verify_text'
     # ./build/.gems/gems/capybara-3.37.1/lib/capybara/node/base.rb:83:in `synchronize'
     # ./build/.gems/gems/capybara-3.37.1/lib/capybara/node/matchers.rb:861:in `_verify_text'
     # ./build/.gems/gems/capybara-3.37.1/lib/capybara/node/matchers.rb:676:in `assert_text'
     # ./build/.gems/gems/capybara-3.37.1/lib/capybara/rspec/matchers/have_text.rb:10:in `element_matches?'
     # ./build/.gems/gems/capybara-3.37.1/lib/capybara/rspec/matchers/base.rb:51:in `matches?'
```

## Steps to reproduce
A simple `expect(find('div').shadow_root).to have_text('some text')` causes the error.

**Comment by twalpole** [comment]
You need to find elements inside the shadow root to use normal methods

**Comment by boris-petrov** [comment]
So there is no way of searching for text in the "whole" shadow DOM?

**Comment by twalpole** [comment]
Not with the current webdriver shadow root spec and selenium implementation

**Comment by boris-petrov** [comment]
I see, thanks! I'll leave you to decide whether to close the issue in that case. But you could add a nicer error message that this is not supported or something.

**Comment by twalpole** [comment]
Closing via https://github.com/teamcapybara/capybara/pull/2596
