### ISSUE TITLE
Update Puma to version 6.0 breaks

### ISSUE THREAD

**Issue by mateoqac** [teamcapybara/capybara#2599]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:
3.37.1

Driver Information (and browser if relevant):

selenium_chrome_headless

## Actual Behavior
Upgrade puma to version 6.0 breaks a feautre test.

```
     1.1) Failure/Error: events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio
          
          NoMethodError:
            undefined method `stdio' for Puma::Events:Class
          
              events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio
                                                                                      ^^^^^^
          # /Users/mateo/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara/registrations/servers.rb:32:in `block in <top (required)>'
          # /Users/mateo/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara.rb:253:in `run_default_server'
          # /Users/mateo/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara/registrations/servers.rb:4:in `block in <top (required)>'
          # /Users/mateo/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara/server.rb:77:in `block in boot'
          # 
          #   Showing full backtrace because every line was filtered out.
          #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
          #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
```

**Comment by simi** [comment]
It is good practice to search for similar issue before reporting problem.

https://github.com/teamcapybara/capybara/pull/2530

Already fixed, waiting for release.
