### ISSUE TITLE
`Capybara::RackTest::Form` yields error

### ISSUE THREAD

**Issue by motine** [teamcapybara/capybara#2628]
## Meta
Capybara Version:
3.38.0

Driver Information (and browser if relevant):
RackTest

## Expected Behavior

The following code should work:

```ruby
form = find('form')
Capybara::RackTest::Form.new(page.driver, form.native).submit({})
```

## Actual Behavior

It yields an error:

```plain
/usr/local/bundle/gems/capybara-3.38.0/lib/capybara/rack_test/driver.rb:53:in `submit': wrong number of arguments (given 4, expected 3) (ArgumentError)
        from /usr/local/bundle/gems/capybara-3.38.0/lib/capybara/rack_test/form.rb:57:in `submit'
[...]
```

## Steps to reproduce

see above

## Background

I needed to submit a form without a submit button. Usually, the form is submitted via a JavaScript onchange handler. Since, I am using RackTest this is not an option. After some research, I found this [Stackoverflow answer](https://stackoverflow.com/a/37368205/4007237). Turns out that the proposed solution stopped working. After some investigation, it became clear, that there is some issue:

```ruby
# lib/capybara/rack_test/form.rb
def submit(button)
    # ...
  driver.submit(method, action.to_s, params(button), content_type: native['enctype']) # passes 4 arguments
end

# lib/capybara/rack_test/driver.rb
def submit(method, path, attributes) # only receives 3 arguments
  # ...
end
```

Please let me know if I am missing something. If my guess (as to what the problem is) is correct, please let me know. I am happy to provide a merge request.

**Comment by motine** [comment]
thank you for your answer. maybe, my description was misleading. the form itself does not need javascript to be submitted, it is just lacking a submit button, so the form is usually submitted via javascript.

here is my defensive answer: i found solutions which have worked on stackoverflow. my guess is that people needed this in the past too. i monkey-patched it in my project and now it works fine (without having to pull in a JS capable driver). also, the code in submit clearly has a problem (or am i missing something) because it calls the method in the driver with the wrong signature. this alone would qualify for a fix.

anyway, i do not really want to be defensive and would rather focus on how we can improve this issue. so what is you suggestion how to solve the use case described above?

**Comment by motine** [comment]
ah i see, i did not understand that driver is actually an instance of browser. sorry for the misunderstanding.

maybe i did not make my use case clear enough: i need a way to submit a form without clicking on the submit button with rack-test. the project does not have a javascript enabled driver and we decided not to implement one.

so far i have solved the issue with the following code (adapted from the classes mentioned above):

```ruby
capybara_form = Capybara::RackTest::Form.new(page.driver, form.native)
method = capybara_form.send(:request_method)
action = form.native['action']
values = capybara_form.send(:params, {})
page.driver.submit(method, action.to_s, values)
```

as the [stackoverflow question](https://stackoverflow.com/a/37368205/4007237) shows, i am not the only one with this problem. what is you suggestion how to solve the use case described above?

**Comment by twalpole** [comment]
My suggestion, as stated previously, is that if you're testing a form which requires JS to function you should be testing that functionality with a JS capable driver otherwise your tests are pointless, imo.

**Comment by motine** [comment]
alright. i seem to fail to describe my use case. nevermind.

**Comment by elliterate** [comment]
@twalpole Can't a user submit a form without a button by pressing the "enter" or "return" key within a text field? Strictly speaking, that doesn't require any JavaScript. I could imagine, then, that they might wish to test such a form using something like this:

```ruby
require 'rspec/autorun'
require 'capybara/rspec'

Capybara.app = lambda do |env|
  params = Rack::Utils.parse_nested_query(env['QUERY_STRING'])

  status = 200
  body = nil

  case env['PATH_INFO']
  when '/'
    body =
      <<~HTML
        <!doctype html>
        <html>
          <body>
            <form action="/search">
              <input type="text" placeholder="Query" name="q" />
            </form>
          </body>
        </html>
      HTML
  when '/search'
    body =
      <<~HTML
        <!doctype html>
        <html>
          <body>
            <p>Your search for #{params['q'].inspect} returned zero results.</p>
          </body>
        </html>
      HTML
  else
    status = 404
  end

  [status, {}, [body]]
end

RSpec.describe 'an HTML form without a button', type: :feature do
  it 'submits with the "enter" or "return" key' do
    visit '/'

    fill_in 'Query', with: "widgets\n"

    expect(page).to have_text('Your search for "widgets" returned zero results.')
  end
end
```

**Comment by twalpole** [comment]
Not since HTML 2.0, and the spec changed after that.  My opinion is that if you're submitting forms via JS then you should be testing them with JS because otherwise the test is pointless. If you disagree with that opinion you are free to monkeypatch or fork this gem.

**Comment by motine** [comment]
thanks, @elliterate for trying. i think there is a very clear opinion on what are allowed use cases and what does not make sense.

**Comment by elliterate** [comment]
I found a section of the current HTML spec that describes this behavior under the name of "implicit submission": https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission

If I'm reading it correctly, it's only applicable when there's exactly _one_ text-like input. That is, a user agent may support implicit submission for this form:

```html
<form>
  <input type="text" name="a" />
</form>
```

But not for this one:

```html
<form>
  <input type="text" name="a" />
  <input type="text" name="b" />
</form>
```

From a quick test on my local machine, Safari, Chrome, and Firefox all seem to do exactly that.

And while the spec doesn't appear to require it, it does say that "user agents are strongly encouraged to support this."

**Comment by jagthedrummer** [comment]
It should definitely be possible to submit a form without a button. Pinning capybara to `3.37.1` gets things to work, but it would be nice if newer versions would continue to support this valid use case.

**Comment by twalpole** [comment]
https://github.com/teamcapybara/capybara/commit/6b05e5cb30e9807483c2641e9a60d89692bb0487

**Comment by motine** [comment]
very nice. thank you for adding this @twalpole.

**Comment by Jell** [comment]
For anyone else looking for a workaround to this in 2025, this is what I use in one of our projects:

```ruby
form = Capybara::RackTest::Form.new(page.driver.browser, find("form").native)
form.submit(form)
```

My use case: I have a form with a submit button that has a formaction and formmethod, but also can be submitted using javascript to refresh some information on the page. Basically the form has `method="GET" action="/refresh"`, while the button has `formaction="POST" action="/create"`.

So the form works without javascript, but I also wanted to test the information refresh without using a JS browser (because that's slower and more flakey).

An alternative solution would be for me to add a hidden button without formaction and formmethod, and to click it. But I'd rather not add unnecessary elements on the page for the sole purpose of testing.
