### ISSUE TITLE
xpath problem with selenium after upgrading from 3.32.2

### ISSUE THREAD

**Issue by sitano** [teamcapybara/capybara#2629]
## Meta

Capybara Version:

         3.38.0

after upgrading from 3.32.2.

Driver Information (and browser if relevant):

        capybara (3.38.0)
          addressable
          matrix
          mini_mime (>= 0.1.3)
          nokogiri (~> 1.8)
          rack (>= 1.6.0)
          rack-test (>= 0.6.3)
          regexp_parser (>= 1.5, < 3.0)
          xpath (~> 3.2)
        capybara-screenshot (1.0.26)
          capybara (>= 1.0, < 4)
          launchy
        capybara-selenium (0.0.6)
          capybara
          selenium-webdriver

         (Session info: chrome=74.0.3729.169)
         (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 5.4.0-1083-aws x86_64)

## Expected Behavior

It must work.

## Actual Behavior

```
Selenium::WebDriver::Error::InvalidSelectorError:
       invalid selector: Unable to locate an element with the xpath expression [] because of the following error:
       SyntaxError: Failed to execute 'evaluate' on 'Document': The string '[]' is not a valid XPath expression.
         (Session info: chrome=74.0.3729.169)
         (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 5.4.0-1083-aws x86_64)
     Shared Example Group: "..." called from ./spec/...
     Shared Example Group: "organization settings" called from ./spec/...

     # ./vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
     # ./vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
     # ./vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
     # ./vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
     # ./vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
     # ./vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
     # ./vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
     # ./vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/oss/bridge.rb:587:in `execute'
     # ./vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/oss/bridge.rb:564:in `find_elements_by'
     # ./vendor/bundle/ruby/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/search_context.rb:80:in `find_elements'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/selenium/extensions/find.rb:17:in `find_by'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/selenium/extensions/find.rb:7:in `find_xpath'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/node/base.rb:119:in `find_xpath'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/queries/selector_query.rb:259:in `find_nodes_by_selector_format'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/queries/selector_query.rb:166:in `block in resolve_for'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/node/base.rb:77:in `synchronize'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/queries/selector_query.rb:165:in `resolve_for'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/node/matchers.rb:844:in `block in _verify_selector_result'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/node/base.rb:84:in `synchronize'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/node/matchers.rb:843:in `_verify_selector_result'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/node/matchers.rb:110:in `assert_selector'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/session.rb:773:in `assert_selector'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/rspec/matchers/have_selector.rb:18:in `element_matches?'
     # ./vendor/bundle/ruby/2.7.0/gems/capybara-3.38.0/lib/capybara/rspec/matchers/base.rb:51:in `matches?'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/handler.rb:51:in `block in handle_matcher'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/expectation_target.rb:101:in `to'
```

## Steps to reproduce

I don't know at the moment. I don't observe it locally but we see it inside of the CI.

**Comment by twalpole** [comment]
Without knowing what code you're calling it's impossible to diagnose this. I will note that Chrome 74 is ancient (released in 2019) - so not really sure why you're testing with that...

**Comment by sitano** [comment]
We have found out we have overloaded where() clause on Enumarator.
