### ISSUE TITLE
Selenium::WebDriver::Remote::Driver needs :options to be set with selenium-webdriver 4.8.0, works with 4.7.1

### ISSUE THREAD

**Issue by doits** [teamcapybara/capybara#2637]
## Meta
Capybara Version: 3.38.0

Driver Information (and browser if relevant): selenium-webdriver 4.8.0 with :remote browser

## Expected Behavior

Tests run like with selenium-webdriver 4.7.1. 

## Actual Behavior

```rb
driven_by :selenium, using: :remote, screen_size: [1400, 2000], options: { url: REMOTE_URL }
```

```
ArgumentError:
   Selenium::WebDriver::Remote::Driver needs :options to be set
 # /vendor/bundle/ruby/3.2.0/gems/selenium-webdriver-4.8.0/lib/selenium/webdriver/remote/driver.rb:53:in `process_options'
 # /vendor/bundle/ruby/3.2.0/gems/selenium-webdriver-4.8.0/lib/selenium/webdriver/remote/driver.rb:36:in `initialize'
 # /vendor/bundle/ruby/3.2.0/gems/selenium-webdriver-4.8.0/lib/selenium/webdriver/common/driver.rb:57:in `new'
 # /vendor/bundle/ruby/3.2.0/gems/selenium-webdriver-4.8.0/lib/selenium/webdriver/common/driver.rb:57:in `for'
 # /vendor/bundle/ruby/3.2.0/gems/selenium-webdriver-4.8.0/lib/selenium/webdriver.rb:88:in `for'
 # /vendor/bundle/ruby/3.2.0/gems/capybara-3.38.0/lib/capybara/selenium/driver.rb:83:in `browser'
 # /vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.4.1/lib/action_dispatch/system_testing/driver.rb:64:in `block in register_selenium'
 # /vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.4.1/lib/action_dispatch/system_testing/driver.rb:63:in `register_selenium'
 # /vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.4.1/lib/action_dispatch/system_testing/driver.rb:49:in `block in register'
 # /vendor/bundle/ruby/3.2.0/gems/capybara-3.38.0/lib/capybara/session.rb:105:in `driver'
 # /vendor/bundle/ruby/3.2.0/gems/capybara-3.38.0/lib/capybara/session.rb:91:in `initialize'
 # /vendor/bundle/ruby/3.2.0/gems/capybara-3.38.0/lib/capybara.rb:421:in `new'
 # /vendor/bundle/ruby/3.2.0/gems/capybara-3.38.0/lib/capybara.rb:421:in `block in session_pool'
 # /vendor/bundle/ruby/3.2.0/gems/capybara-3.38.0/lib/capybara.rb:317:in `current_session'
 # /vendor/bundle/ruby/3.2.0/gems/capybara-3.38.0/lib/capybara/dsl.rb:46:in `page'
 # /vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.4.1/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:99:in `save_image'
 # /vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.4.1/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:36:in `take_screenshot'
 # /vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.4.1/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:45:in `take_failed_screenshot'
 # /vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.4.1/lib/action_dispatch/system_testing/test_helpers/setup_and_teardown.rb:8:in `before_teardown'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-rails-6.0.1/lib/rspec/rails/example/system_example_group.rb:110:in `call'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-rails-6.0.1/lib/rspec/rails/example/system_example_group.rb:110:in `block (2 levels) in <module:SystemExampleGroup>'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:372:in `run'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:528:in `each'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:614:in `each'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:485:in `run'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:518:in `run_after_example'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:283:in `block in run'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `block in run'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-rails-6.0.1/lib/rspec/rails/example/system_example_group.rb:120:in `block (2 levels) in <module:SystemExampleGroup>'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:390:in `execute_with'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-rails-6.0.1/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:390:in `execute_with'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `run'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:259:in `run'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `map'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `run_examples'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:607:in `run'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `map'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/reporter.rb:74:in `report'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:115:in `run_specs'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:89:in `run'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:71:in `run'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:45:in `invoke'
 # /vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.0/exe/rspec:4:in `<top (required)>'
 # /vendor/bundle/ruby/3.2.0/bin/rspec:25:in `load'
 # /vendor/bundle/ruby/3.2.0/bin/rspec:25:in `<top (required)>'
```

## Other

I looked at `processed_options` of https://github.com/teamcapybara/capybara/blob/69abf9e24cc225aca1ef7e25b1bfb7b61017f017/lib/capybara/selenium/driver.rb#L83 and there is indeed no `options` key. It looks like this for me:

```rb
{
  :url=>REMOTE_URL,
  :http_client=>#<Capybara::Selenium::PersistentClient:0x00000001135b9f00 @open_timeout=nil, @read_timeout=nil>
}
```

This seems to work with selenium-webdriver < 4.8.0, but not with 4.8.0 anymore? 🤷 

Not sure where the problem lies (rspec? capybara? selenium-webdriver?), I'm sorry if actually Capybara does everything right and the problem lies elsewhere.

Edit: Looks like [this commit](https://github.com/SeleniumHQ/selenium/commit/d338de3d20bbd6427951a4c1a58989e714bf0d1f#diff-3aaea2060021756f33d0ae33828e19ea2735e55ebd7e391fba89c8adfc8c6d73) introduced the behavior of selenium-webdriver.

**Comment by twalpole** [comment]
`driven_by` is a rails or rspec-rails command, not Capybara.  The driver implementation in one of those needs to be modified, or you need to pass extra options through to it

**Comment by kg8m** [comment]
For your information, Rails has been fixed in https://github.com/rails/rails/pull/47117. Let's wait for its release.
