### ISSUE TITLE
New version of chrome (110) fails with Net::ReadTimeout in headless mode

### ISSUE THREAD

**Issue by mark-davenport-fountain** [teamcapybara/capybara#2644]
Seems like this previous issue had returned in chrome 110. Downgrading to chrome 109 fixes the problem. 
https://github.com/teamcapybara/capybara/issues/2181

This appears to only happen in headless mode. It succeeds otherwise. 

## Meta
Capybara Version:3.38.0
Driver Information (and browser if relevant):
selenium-webdriver 4.8.0
[ChromeDriver 110.0.5481.77](https://chromedriver.storage.googleapis.com/index.html?path=110.0.5481.77/)

Driver configuration
```
Capybara.register_driver :selenium_chrome_headless do |app|
  download_prefs = {
    prompt_for_download: false,
    default_directory: DownloadHelper::PATH
  }

  plugins_prefs = {
    always_open_pdf_externally: true
  }

  options = Selenium::WebDriver::Chrome::Options.new
  options.add_preference(:download, download_prefs)
  options.add_preference(:plugins, plugins_prefs)
  options.add_argument('--window-size=1600,1000')
  options.add_argument('--disable-gpu')
  options.add_argument('--headless')

  Capybara::Selenium::Driver.new(app,
                                 browser: :chrome,
                                 options: options)
end
````

## Expected Behavior

Test succeeds 

## Actual Behavior
```
/Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/net/protocol.rb:219:in `rbuf_fill': Net::ReadTimeout with #<Socket:(closed)> (Net::ReadTimeout)
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/net/protocol.rb:193:in `readuntil'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/net/protocol.rb:203:in `readline'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/net/http/response.rb:42:in `read_status_line'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/net/http/response.rb:31:in `read_new'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:1575:in `block in transport_request'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:1566:in `catch'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:1566:in `transport_request'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:1539:in `request'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.8.0/lib/selenium/webdriver/remote/http/default.rb:119:in `response_for'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.8.0/lib/selenium/webdriver/remote/http/default.rb:77:in `request'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.8.0/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.8.0/lib/selenium/webdriver/remote/bridge.rb:186:in `quit'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.8.0/lib/selenium/webdriver/common/driver.rb:173:in `quit'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/capybara-3.38.0/lib/capybara/selenium/driver.rb:293:in `quit'
	from /Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/capybara-3.38.0/lib/capybara/selenium/driver.rb:519:in `block in setup_exit_handler'
/Users/mark/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': Failed to open TCP connection to 127.0.0.1:9520 (Connection refused - connect(2) for 127.0.0.1:9520) (Errno::ECONNREFUSED)
```

## Steps to reproduce
Run a tests which performs a click on a link to download a file.

**Comment by twalpole** [comment]
Not sure how this can be considered a bug in Capybara, it's either in chromedriver or selenium

**Comment by mark-davenport-fountain** [comment]
Fair enough. Just thought it was interesting that there was a good discussion on a thread in the repo about this exact issue previously. I can go report elsewhere though.

**Comment by scientia-ac-labore** [comment]
It is a  chromedrive bug. `--headless=new` is a possible solution. More [here](https://groups.google.com/g/chromedriver-users/c/iDCjIU0Op7M?pli=1)

**Comment by eliotsykes** [comment]
With a more recent Chrome version, I've recently encountered this in a CI environment, where Chrome quitting raises `Net::ReadTimeout` and fails the build.

This was happening with both `--headless` and `--headless=new` modes.

Here's one workaround to suppress these errors:

```ruby
return unless ENV['CI']

puts "[ChromeGracefulQuit] Applying extension to prevent Chrome quit errors from failing the test suite"

module ChromeGracefulQuit
  def quit
    is_chrome = (@browser&.browser == :chrome)
    super
  rescue Net::ReadTimeout => error
    if is_chrome
      puts "[ChromeGracefulQuit] Net::ReadTimeout error suppressed when quitting Chrome."
    else
      raise error
    end
  end
end

Capybara::Selenium::Driver.prepend ChromeGracefulQuit
```
