### ISSUE TITLE
Does capybara have support for the new headless chrome?

### ISSUE THREAD

**Issue by FireLemons** [teamcapybara/capybara#2650]
## Meta
Capybara Version:
3.38.0
Driver Information (and browser if relevant):
selenium-webdriver 4.8.0 with headless chrome with flag `--headless=new`

## Expected Behavior
No flaking

Edit:
running capybara with a regular chrome driver makes all the tests pass. the new headless version should do the same

## Actual Behavior
Strange flaky tests including alerts not working and `fill_in` not clearing the input before entering data

some test outputs:

```
   1) case_contacts/new when admin with HTML in notes renders HTML correctly on the index page
     Failure/Error: expect(page).to have_css("#case_contacts_list .card h1", text: expected_text)
       expected to find visible css "#case_contacts_list .card h1" with text "Hello world" but there were no matches. Also found "", which matched the selector but not all filters. 

     [Screenshot Image]: /home/runner/work/casa/casa/tmp/capybara/failures_r_spec_example_groups_case_contacts_new_when_admin_with_html_in_notes_renders_html_correctly_on_the_index_page_699.png


     # ./spec/system/case_contacts/new_spec.rb:196:in `block (4 levels) in <top (required)>'
```

```
   1) case_contacts/new volunteer user with invalid inputs sets occured date field to current date when a future date is selected
     Failure/Error: page.accept_alert

     Capybara::ModalNotFound:
       Unable to find modal dialog

     [Screenshot Image]: /home/runner/work/casa/casa/tmp/capybara/failures_r_spec_example_groups_case_contacts_new_volunteer_user_with_invalid_inputs_sets_occured_date_field_to_current_date_when_a_future_date_is_selected_656.png


     # ./spec/system/case_contacts/new_spec.rb:548:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Selenium::WebDriver::Error::TimeoutError:
     #   timed out after 2 seconds (no such alert
     #     (Session info: chrome=110.0.5481.100))
     #   ./spec/system/case_contacts/new_spec.rb:548:in `block (4 levels) in <top (required)>'
```

performing the test steps by hand in the browser produces the expected responses

## Steps to reproduce
fork https://github.com/rubyforgood/casa and run the rspec github actions workflow.

**Comment by twalpole** [comment]
These aren't issues with Capybara, they are recurring issues with chromedriver which Google doesn't care to fix. Read the chromedriver issues list

**Comment by jcoyne** [comment]
@twalpole would it make sense to raise an error/warning that says accept_alert is disabled when using chromedriver?
