### ISSUE TITLE
Failure output doesn't include element text when it matches the locator but it's hidden [only in a browser]

### ISSUE THREAD

**Issue by henrahmagix** [teamcapybara/capybara#2683]
## Meta
Capybara Version: 3.39.2
Driver Information (and browser if relevant):
selenium-webdriver 4.10.0 with Firefox 114.0.2 and Chrome 114.0.5735.198

## Expected Behavior

Test failure output says `Also found "Log out"` for all tests

```
Failures:

  1) visibility of links does not exhibit the issue when invisible in Capybara.string
     Failure/Error: expect(page).to have_link('Log out', visible: :visible)
       expected to find visible link "Log out" but there were no matches. Also found "Log out", which matched the selector but not all filters. 
     # ./visibility_spec.rb:61:in `block (2 levels) in <main>'

  2) visibility of links exhibits the issue when invisible in browser
     Failure/Error: expect(page).to have_link('Log out', visible: :visible)
         expected to find visible link "Log out" but there were no matches. Also found "Log out", which matched the selector but not all filters. 
     # ./visibility_spec.rb:76:in `block (2 levels) in <main>'
```

## Actual Behavior

Test failure output says `Also found ""` for `it exhibits the issue when invisible in browser`

but it correctly outputs `Also found "Log out"` for `it does not exhibit the issue when invisible in Capybara.string`

```
Failures:

  1) visibility of links does not exhibit the issue when invisible in Capybara.string
     Failure/Error: expect(page).to have_link('Log out', visible: :visible)
       expected to find visible link "Log out" but there were no matches. Also found "Log out", which matched the selector but not all filters. 
     # ./visibility_spec.rb:61:in `block (2 levels) in <main>'

  2) visibility of links exhibits the issue when invisible in browser
     Failure/Error: expect(page).to have_link('Log out', visible: :visible)
     
       Selenium is not reporting the text of matching elements when those elements are hidden, thus making a hard-to-debug failure message.
     
       Original failure:
         expected to find visible link "Log out" but there were no matches. Also found "", which matched the selector but not all filters. 
     # ./visibility_spec.rb:76:in `block (2 levels) in <main>'
```

## Steps to reproduce
Run this rile with `ruby <file>`

FYI the tests are meant to fail, so the _real_ test here for this issue is whether or not the test failure output includes the matching elements text.
```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem 'webdrivers'
  gem 'selenium-webdriver'
  gem 'capybara'
  gem 'rspec'
end

require 'capybara'
require 'capybara/rspec'
require 'selenium/webdriver'

Capybara.default_max_wait_time = 0
# Capybara.ignore_hidden_elements = false # uncommenting this is a workaround, but it's not a nice one

# This issue is apparent with both Geckodriver and Chromedriver, so any option below works.
# Capybara.javascript_driver = :selenium
Capybara.javascript_driver = :selenium_headless
# Capybara.javascript_driver = :selenium_chrome
# Capybara.javascript_driver = :selenium_chrome_headless

puts "Ruby version is: #{RUBY_VERSION}"
require 'rspec/autorun'

RSpec.describe 'visibility of links', type: :feature, js: true do
  after do |example|
    next unless example.exception

    # Explain the issue in the failure message.
    if example.exception.message.include?('Also found ""')
      new_exception = example.exception.class.new(
        "Selenium is not reporting the text of matching elements when those" \
        " elements are hidden, thus making a hard-to-debug failure message." \
        "\n\nOriginal failure:\n  #{example.exception.message}"
      )
      new_exception.set_backtrace(example.exception.backtrace)
      example.display_exception = new_exception
    end
  end
  
  # This test failure reports:
  #   Also found "Log out", which matched the selector but not all filters.
  # which is helpful because at least we can see that the `Log out` link exists.
  # It would be nicer if the failure output said specifically that it's hidden.
  it 'does not exhibit the issue when invisible in Capybara.string' do
    page = Capybara.string <<~HTML
      <p>This is my page</p>
      <a style="display:none;" href="/logout">Log out</a>
    HTML

    expect(page).to have_link('Log out', visible: :visible)
  end

  # This test failure reports:
  #   Also found "", which matched the selector but not all filters.
  # which is unfortunately unhelpful, because it sounds like the `Log out` link
  # does not exist.
  it 'exhibits the issue when invisible in browser' do
    visit 'http://example.com'
    execute_script <<~JS
      document.body.innerHTML =
        '<p>This is my page</p>' +
        '<a style="display:none;" href="/logout">Log out</a>'
    JS

    expect(page).to have_link('Log out', visible: :visible)
  end

  it 'what are the session_query_options for matchers?' do
    visit 'http://example.com'
    puts Capybara.current_session.driver.session_options.inspect
    # Does `visible_text_only` have anything to do with it?
    #<Capybara::SessionConfig:0x000000011a4af220 @server_host=nil, @always_include_port=false, @run_server=true, @default_selector=:css, @default_max_wait_time=0, @default_retry_interval=0.01, @ignore_hidden_elements=true, @default_host="http://www.example.com", @automatic_reload=true, @match=:smart, @exact=false, @exact_text=false, @raise_server_errors=true, @server_errors=[Exception], @visible_text_only=false, @automatic_label_click=false, @enable_aria_label=false, @enable_aria_role=false, @default_set_options={}, @test_id=nil, @predicates_wait=true, @default_normalize_ws=false, @w3c_click_offset=true>
  end
end
```

**Comment by henrahmagix** [comment]
I have a feeling that the matchers should query the browser page again if they found matching hidden elements for an assertion that requires them to be visible, so those elements can be picked up _with_ their text contents? I wasn't sure how to patch this myself, so I'm posting here hoping that it's a not-too-complicated change to make, if accepted?

**Comment by twalpole** [comment]
This is expected behavior -- you've asked to find visible elements and Capybara has found elements that match but are showing no contents in the page.  When using Capybara.string it outputs a different value because Capybara.string processes only a tiny amount of CSS, and is generally a bad approximation of a browser.  It is designed for pretty limited usage and it's shortcomings are well documented, use only if you know what you're doing and need faster execution but with known and understood limitations.
