### ISSUE TITLE
Headless Chrome Capybara::Driver::Base#accept_modal (Capybara::NotSupportedByDriverError)

### ISSUE THREAD

**Issue by joshuacronemeyer** [teamcapybara/capybara#2789]
Hi there,

I get this error when trying to interact with an alert with Capybara using headless chrome. I would have posted this in the google group but when I go there it is just a message saying "Capybara has been identified as containing spam, malware, or other malicious content." and i can't post or see posts there.

## Meta
Capybara Version: 3.40.0
Driver Information (and browser if relevant): selenium-webdriver 4.27.0 chrome 131.0.6778.109 with headless flag

## Expected Behavior
accept_modal will close the alert

## Actual Behavior

```
app/models/permit.rb:252:in `go_to_permit_detail': Capybara::Driver::Base#accept_modal (Capybara::NotSupportedByDriverError)
	from app/models/permit.rb:231:in `fetch_permit_detail'
	from app/sidekiq/get_permit_details_job.rb:21:in `block in perform'
	from app/sidekiq/get_permit_details_job.rb:20:in `perform'
	from (****):1:in `<main>'
```

**Comment by jcoyne** [comment]
I think this may be related to https://issues.chromium.org/issues/351858989

**Comment by joshuacronemeyer** [comment]
I got an email about a comment that says "I think this may be related to https://issues.chromium.org/issues/351858989" but i guess the comment was deleted. If that chrome issue is the blocker here then it looks like it's moving really slow to get chrome to take action on it and that most people downgrade to chrome 126 to work around it? It's a major bummer because when somebody pops an alert you just can't do anything and when you try to do something Selenium::WebDriver::Error::UnexpectedAlertOpenError gets raised.
