### ISSUE TITLE
Visiting a relative URL doesn't work when server hasn't been started.

### ISSUE THREAD

**Issue by jnicklas** [teamcapybara/capybara#861]
See this gist for an example of this issue: https://gist.github.com/a1a5fe787dfc698e05ba

This seems to occur when:
- `Capybara.app` is not set or `Capybara.run_server` is false
- `Capybara.app_host` is set
- `visit` is called with a relative URL

In which case, an Exception like the following is thrown:

```
Selenium::WebDriver::Error::UnknownError: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService.newURI]
from /Users/dev/.rvm/gems/ruby-1.9.3-p286/gems/selenium-webdriver-2.26.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
```

**Comment by cihad** [comment]
`spec/rails_helper.rb`:

~~~ruby
# ... 
require 'capybara/rails'
require 'capybara/rspec'
Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome)
end
# ...
~~~

`spec/features/content_spec.rb`:

~~~ruby
require "rails_helper"

feature "Content" do
  
  let(:user) { create :authenticated }

  before do
    login user
  end

  scenario "User creates a new content", driver: :chrome do
    visit "nodes/new/content"
    click_link "New content"

    fill_in "content_title", with: "Example Title"
    fill_in "content_body", with: "Example Body"

    click_on "Submit"

    expect(page).to have_content "Example Title"
    expect(page).to have_content "Example Body"

  end

end
~~~

I got this error:
~~~
F

Failures:

  1) Content User creates a new content
     Failure/Error: login user
     Selenium::WebDriver::Error::UnknownError:
       unknown error: unhandled inspector error: {"code":-32603,"message":"Cannot navigate to invalid URL"}
         (Session info: chrome=41.0.2272.101)
         (Driver info: chromedriver=2.9.248316,platform=Linux 3.16.0-33-generic x86)
     # ./spec/support/helpers/test_helpers.rb:11:in `login'
     # ./spec/features/content_spec.rb:8:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'

Finished in 2.23 seconds (files took 0.36191 seconds to load)
1 example, 1 failure

~~~

When i am using `:selenium` driver:

~~~
F

Failures:

  1) Content User creates a new content
     Failure/Error: login user
     Selenium::WebDriver::Error::UnknownError:
       f.QueryInterface is not a function
     # [remote server] file:///tmp/webdriver-profile20150331-7206-1fder92/extensions/fxdriver@googlecode.com/components/driver-component.js:10132:in `FirefoxDriver.prototype.get'
     # [remote server] file:///tmp/webdriver-profile20150331-7206-1fder92/extensions/fxdriver@googlecode.com/components/command-processor.js:12274:in `DelayedCommand.prototype.executeInternal_/h'
     # [remote server] file:///tmp/webdriver-profile20150331-7206-1fder92/extensions/fxdriver@googlecode.com/components/command-processor.js:12279:in `DelayedCommand.prototype.executeInternal_'
     # [remote server] file:///tmp/webdriver-profile20150331-7206-1fder92/extensions/fxdriver@googlecode.com/components/command-processor.js:12221:in `DelayedCommand.prototype.execute/<'
     # ./spec/support/helpers/test_helpers.rb:11:in `login'
     # ./spec/features/content_spec.rb:8:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'

Finished in 5.46 seconds (files took 0.35364 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/content_spec.rb:11 # Content User creates a new content

~~~

How can i fix this problem?

**Comment by twalpole** [comment]
@cihad Please post how to questions on the mailing list as requested in the README, rather than tacking them on to issues that have been closed for well over 2 years
